/**
 * Registry unificado de erros LEDI (FAO/FAI/PROC) + Previne ESB.
 * Espelho de apps/api/src/care-extra/ledi-error-registry.ts — o teste CI exige paridade.
 *
 * repairClass (caminho A–E):
 *   auto | semi | individual | reexport | info
 * implemented: se a correção já roda hoje (fixer/UI).
 */

export type LediSeverity = 'BLOCKER' | 'MONEY_RISK' | 'QUALITY_WARN' | 'INFO';
export type LediChannel = 'LEDI' | 'PREVINE' | 'LOTE';
export type LediRepairClass = 'auto' | 'semi' | 'individual' | 'reexport' | 'info';
export type LediFichaTipo = 'FAO' | 'FAI' | 'PROC';

export type LediErrorDef = {
  code: string;
  severity: LediSeverity;
  channel: LediChannel;
  title: string;
  why: string;
  how: string;
  field?: string;
  repairClass: LediRepairClass;
  /** false = caminho planejado; UI usa fallback individual/reexport até P1/P2 */
  implemented: boolean;
  ui?: string;
  focusField?: string;
  tipos: LediFichaTipo[];
  note?: string;
};

export const LEDI_ERROR_REGISTRY: Record<string, LediErrorDef> = {
  ALTA_EPISODIO_RULE: {
    code: 'ALTA_EPISODIO_RULE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Alta do episódio sem regra de consulta',
    why: 'A conduta de alta do episódio exige combinação válida com o tipo de consulta. Sem isso, a ficha é rejeitada e a linha de cuidado do paciente fica inconsistente nos sistemas federais.',
    how: 'Ajuste conduta e tipo de consulta conforme a regra da ficha. Peça orientação ao dentista ou à coordenação de odontologia.',
    field: 'consulta',
    repairClass: 'individual',
    implemented: true,
    focusField: 'consulta',
    tipos: ['FAO'],
  },
  ATENDIMENTOS_EMPTY: {
    code: 'ATENDIMENTOS_EMPTY',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ficha sem nenhum atendimento',
    why: 'A ficha “mãe” precisa ter pelo menos um atendimento odontológico de paciente. Sem pacientes dentro, não há produção para enviar — envelope vazio.',
    how: 'Inclua ao menos um bloco de atendimento no XML, ou confira se o export não saiu incompleto.',
    field: 'xml',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  ATENDIMENTOS_MAX: {
    code: 'ATENDIMENTOS_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Ficha com pacientes demais',
    why: 'Há um limite de 99 atendimentos por ficha. Passou disso, o Ministério pode rejeitar o lote inteiro e a cidade perde vários registros de uma vez.',
    how: 'Divida em mais de uma ficha (vários arquivos/masters) e envie em partes.',
    field: 'xml',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  CBO_MISSING: {
    code: 'CBO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a ocupação do profissional',
    why: 'É preciso informar o código de ocupação (dentista, técnico ou auxiliar de saúde bucal). Sem isso, o Ministério não reconhece que o atendimento é de odontologia elegível e rejeita a ficha.',
    how: 'Preencha o código de ocupação na lotação (ex.: dentista 223208). Peça ao RH/CNES se o vínculo estiver incompleto.',
    repairClass: 'auto',
    implemented: true,
    ui: 'cbo',
    tipos: ['FAO'],
  },
  CBO_NOT_ODONTO: {
    code: 'CBO_NOT_ODONTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ocupação não é de saúde bucal',
    why: 'A ocupação informada não é de dentista, técnico ou auxiliar de saúde bucal. Só esses profissionais podem registrar a ficha odontológica. Com ocupação errada, a produção não vale para odontologia.',
    how: 'Troque para a ocupação correta do profissional de saúde bucal na lotação e reexporte.',
    repairClass: 'auto',
    implemented: true,
    ui: 'cbo',
    tipos: ['FAO'],
  },
  CIAP_FORMAT: {
    code: 'CIAP_FORMAT',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'CIAP com formato a normalizar',
    why: 'O código CIAP veio com espaço ou minúscula. O Ministério espera o padrão letra + 2 dígitos (ex.: A98). Sem normalizar, a ficha pode ser rejeitada ou o diagnóstico não entra na produção.',
    how: 'Normaliza para maiúsculas sem espaços quando o padrão for recuperável. Não inventa diagnóstico.',
    repairClass: 'auto',
    implemented: true,
    focusField: 'ciap',
    tipos: ['FAI'],
  },
  CID_FORMAT: {
    code: 'CID_FORMAT',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'CID-10 com formato a normalizar',
    why: 'O CID veio com espaço ou minúscula. Formato estranho pode falhar no Siaps e o problema clínico não conta.',
    how: 'Normaliza para maiúsculas sem espaços quando o padrão for recuperável. Não chuta CID.',
    repairClass: 'auto',
    implemented: true,
    focusField: 'cid10',
    tipos: ['FAI'],
  },
  CNES_FORMAT: {
    code: 'CNES_FORMAT',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Código da unidade com formato errado',
    why: 'O código da unidade precisa ter exatamente 7 dígitos. Número com tamanho errado (comum em sistemas antigos) faz o Ministério rejeitar — a produção da unidade não conta.',
    how: 'Use o código oficial de 7 dígitos da unidade e reexporte.',
    repairClass: 'auto',
    implemented: true,
    ui: 'cnes',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  CNES_MISSING: {
    code: 'CNES_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o código da unidade de saúde',
    why: 'Toda produção precisa apontar para a unidade (o “CNES” — número oficial do estabelecimento). Sem ele, o Ministério não sabe de qual posto veio o atendimento e rejeita o envio.',
    how: 'Preencha o código da unidade com 7 dígitos (o número oficial do estabelecimento). Confira no cadastro da UBS.',
    repairClass: 'auto',
    implemented: true,
    ui: 'cnes',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  CNS_INVALID: {
    code: 'CNS_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Cartão do cidadão inválido',
    why: 'O número do Cartão Nacional de Saúde falhou na checagem (dígito verificador). Costuma ser digitação errada no sistema antigo. Sem identificação válida, a produção não conta.',
    how: 'Corrija o CNS no cadastro do cidadão ou use um CPF válido e gere o arquivo de novo.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  CNS_FORMAT: {
    code: 'CNS_FORMAT',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'Cartão do cidadão com espaços ou pontuação',
    why: 'O número do cartão passa na checagem, mas veio com ponto, traço ou espaço. O Ministério pode rejeitar o valor “sujo”.',
    how: 'Remove caracteres que não são dígitos quando o checksum já é válido. Não inventa CNS.',
    repairClass: 'auto',
    implemented: true,
    focusField: 'cns',
    tipos: ['FAI'],
  },
  CONDUTA_MISSING: {
    code: 'CONDUTA_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a conduta / encaminhamento',
    why: 'Todo atendimento individual (FAI tipo 4) precisa registrar o que ficou combinado ao final (alta, retorno, encaminhamento etc. — catálogo TipoEncaminhamentoIndividual). Sem conduta, o Ministério rejeita e a produção não conta.',
    how: 'Inclua ao menos uma conduta FAI (não use condutas odonto). Peça ao profissional da APS para registrar alta, retorno ou encaminhamento na ficha.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'condutas',
    tipos: ['FAI'],
  },
  CONDUTAS_MAX: {
    code: 'CONDUTAS_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Condutas em excesso',
    why: 'Há um limite de itens na lista de condutas. Passou do máximo, o envio pode ser rejeitado e vários atendimentos do lote ficam em risco.',
    how: 'Reduza a lista de condutas ao essencial (máximo 17). O lote pode truncar automaticamente mantendo as 17 primeiras.',
    field: 'xml',
    repairClass: 'auto',
    implemented: true,
    focusField: 'condutas',
    tipos: ['FAO', 'FAI'],
  },
  CONDUTAS_MISSING: {
    code: 'CONDUTAS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a conduta / encaminhamento',
    why: 'Todo atendimento odontológico precisa dizer o que ficou combinado ao final (alta, retorno, encaminhamento, tratamento concluído, etc.). Sem conduta, o Ministério rejeita — e indicadores como “tratamento concluído” não têm como nascer.',
    how: 'Inclua ao menos uma conduta/encaminhamento odonto (códigos 1 a 17). Peça ao dentista para registrar a conduta na ficha.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  CPF_CNS_BOTH: {
    code: 'CPF_CNS_BOTH',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CPF e cartão do cidadão juntos',
    why: 'Na ficha odontológica, no mesmo atendimento, informe CPF ou o Cartão Nacional de Saúde do cidadão — nunca os dois ao mesmo tempo. Com os dois, o Ministério rejeita e a produção da pessoa não conta.',
    how: 'Deixe só um identificador (a preferência local costuma ser o cartão do cidadão). Remova o outro e reexporte.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  CPF_INVALID: {
    code: 'CPF_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CPF do cidadão inválido',
    why: 'O CPF não passa na checagem oficial de dígitos. Em geral é erro de digitação. Com CPF inválido, o Ministério rejeita e a produção da pessoa não entra.',
    how: 'Corrija o CPF no cadastro do cidadão ou use um cartão do cidadão (CNS) válido e reexporte.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  CPF_FORMAT: {
    code: 'CPF_FORMAT',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'CPF com espaços ou pontuação',
    why: 'O CPF passa na checagem, mas veio formatado. O envio pode recusar o valor com pontos/traços.',
    how: 'Remove caracteres que não são dígitos quando o checksum já é válido. Não inventa CPF.',
    repairClass: 'auto',
    implemented: true,
    focusField: 'cpf',
    tipos: ['FAI'],
  },
  DATA_ATENDIMENTO_MISSING: {
    code: 'DATA_ATENDIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a data do atendimento',
    why: 'Sem a data, o Ministério não sabe em qual mês/competência lançar a produção. A ficha é rejeitada e aquele dia de trabalho não entra no relatório da cidade.',
    how: 'Preencha a data do atendimento no cabeçalho da ficha e reexporte.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  DT_NASCIMENTO_MISSING: {
    code: 'DT_NASCIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a data de nascimento',
    why: 'Sem data de nascimento o Ministério não individualiza bem o paciente (idade, vínculo). A ficha é rejeitada e o atendimento não entra na produção.',
    how: 'Complete a data de nascimento no cadastro do cidadão e reexporte a ficha.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'nascimento',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  DT_NASCIMENTO_AFTER_ATEND: {
    code: 'DT_NASCIMENTO_AFTER_ATEND',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Nascimento depois do atendimento',
    why: 'A data de nascimento ficou depois da data do atendimento — inconsistência. O Ministério rejeita e aquele registro não conta.',
    how: 'Corrija a data de nascimento no cadastro ou a data do atendimento. Não inventamos data.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'nascimento',
    tipos: ['FAI'],
  },
  FAI_ATENDIMENTO_MISSING: {
    code: 'FAI_ATENDIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'FAI sem atendimento',
    why: 'A ficha individual não traz o bloco de atendimento. Sem isso a produção não conta.',
    how: 'Reexporte a ficha com ao menos um atendimento preenchido.',
    repairClass: 'reexport',
    implemented: true,
    tipos: ['FAI'],
  },
  FAI_ROOT_NOT_FOUND: {
    code: 'FAI_ROOT_NOT_FOUND',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ficha individual incompleta',
    why: 'Faltam partes essenciais da ficha de atendimento individual (tipo 4). Sem a raiz correta, o Ministério rejeita o envio.',
    how: 'Reexporte o XML completo da FAI no sistema de origem. Use a tela /faturamento/lote/fai.',
    repairClass: 'reexport',
    implemented: true,
    tipos: ['FAI'],
  },
  FAO_ROOT_NOT_FOUND: {
    code: 'FAO_ROOT_NOT_FOUND',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ficha odontológica incompleta',
    why: 'Faltam partes essenciais da ficha: identificador único, dados da unidade/profissional e a lista de atendimentos. Sem isso, o Ministério rejeita o lote e a cidade perde o registro daquele atendimento.',
    how: 'Envie o XML completo da ficha odontológica, não só um pedaço. Reexporte pelo sistema de origem.',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  FORMAT_DADO_TRANSPORT: {
    code: 'FORMAT_DADO_TRANSPORT',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Envelope sem a ficha odontológica dentro',
    why: 'O arquivo tem o “pacote” de transporte, mas dentro dele não aparece a ficha de atendimento odontológico. Para o Ministério, é como mandar um envelope vazio: a produção do paciente não chega.',
    how: 'Confirme no export que o tipo serializado é 5 (ficha odontológica) e que a ficha master de odontologia está embutida no XML.',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  FORMAT_FHIR_NOT_FAO: {
    code: 'FORMAT_FHIR_NOT_FAO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Arquivo do tipo errado (não é ficha odontológica)',
    why: 'Este arquivo parece ser de outro padrão de dados clínicos (usado em outros envios), e não a ficha de atendimento odontológico que esta tela espera. Se mandar assim, o Ministério não conta como produção de dentista da Atenção Primária.',
    how: 'Na tela ou no sistema legado, use a exportação da ficha odontológica (tipo 5). Não use o arquivo de outro tipo de envio.',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  GESTANTE_MISSING: {
    code: 'GESTANTE_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta informar se é gestante',
    why: 'Mesmo quando a pessoa não está grávida, o campo gestante precisa existir (sim ou não). Campo ausente = rejeição. Isso também afeta cuidados e indicadores de gestantes na cidade.',
    how: 'Sempre emita o campo gestante como true ou false. Peça ao dentista/sistema para não omitir o campo.',
    repairClass: 'auto',
    implemented: true,
    ui: 'gestante',
    tipos: ['FAO'],
  },
  GESTANTE_SEXO_MASC: {
    code: 'GESTANTE_SEXO_MASC',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Marcado gestante com sexo masculino',
    why: 'Há inconsistência: gestante = sim e sexo = masculino. O Ministério rejeita por erro lógico. Além disso, indicadores de gestantes ficam distorcidos se isso passasse.',
    how: 'Corrija o sexo ou desmarque gestante. Peça ao profissional para revisar o prontuário.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'gestante',
    tipos: ['FAO'],
  },
  HORA_FIM_ANTES_INI: {
    code: 'HORA_FIM_ANTES_INI',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Fim do atendimento antes do início',
    why: 'O horário final está antes do inicial — impossível na prática. O Ministério rejeita por inconsistência e aquele atendimento não conta.',
    how: 'Corrija as marcas de tempo no prontuário e reexporte. Peça ao dentista/recepção para revisar o horário lançado.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  HORA_FIM_MISSING: {
    code: 'HORA_FIM_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o horário de fim',
    why: 'É obrigatório informar quando o atendimento terminou. Sem horário final, rejeição — produção perdida para a cidade.',
    how: 'Exporte o fim do atendimento. Peça ao profissional para encerrar a consulta no sistema antes de gerar o lote.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  HORA_INI_ANTES_DATA: {
    code: 'HORA_INI_ANTES_DATA',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Início do atendimento antes da data do cabeçalho',
    why: 'O horário do atendimento ficou antes da data informada no cabeçalho da ficha. Isso pode fazer o Ministério rejeitar ou lançar a produção na competência errada — risco de qualidade da informação / indicador no mês errado.',
    how: 'Alinhe a data do cabeçalho com o período real do atendimento e gere o arquivo de novo.',
    field: 'xml',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  HORA_INI_MISSING: {
    code: 'HORA_INI_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o horário de início',
    why: 'O Ministério exige o horário em que o atendimento começou. Sem isso, a ficha é rejeitada e aquele atendimento não entra na produção do dia.',
    how: 'Exporte o início do atendimento a partir do prontuário. Confira se o sistema legado está gravando o horário.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  IBGE_FORMAT: {
    code: 'IBGE_FORMAT',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Código do município inválido',
    why: 'O código do município não tem 7 dígitos numéricos. Com município errado, a produção pode ir para o lugar errado ou ser rejeitada.',
    how: 'Corrija o código do município no cadastro da unidade e gere o arquivo novamente.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ibge',
    tipos: ['FAO', 'FAI'],
  },
  IBGE_MISSING: {
    code: 'IBGE_MISSING',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Falta o código do município',
    why: 'É preciso informar o código IBGE do município para o Ministério saber de qual cidade é a produção. Sem isso, o atendimento pode não ser creditado ao município certo — impacto direto na qualidade da produção e nos indicadores locais.',
    how: 'Cadastre o código IBGE de 7 dígitos do município (Franca = 3516200) no cadastro da unidade e reexporte.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ibge',
    tipos: ['FAO', 'FAI'],
  },
  INE_MISSING: {
    code: 'INE_MISSING',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'Falta o código da equipe',
    why: 'O INE identifica a equipe de saúde. Sem ele, o Ministério às vezes ainda aceita a ficha, mas a produção fica solta — dificulta amarrar o atendimento à equipe certa no Previne Brasil e nos indicadores da cidade.',
    how: 'Preencha o código da equipe (INE) no envelope e na lotação do profissional.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ine',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  JUSTIFICATIVA_CPF_MISSING: {
    code: 'JUSTIFICATIVA_CPF_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta justificativa de não ter CPF',
    why: 'Quando você marca que o cidadão não tem CPF, o Ministério exige o motivo (código de justificativa). Sem isso, a ficha cai na rejeição e o atendimento não conta.',
    how: 'Escolha o motivo na lista (ex.: 5 = situação de rua, 8 = indocumentado, 99 = outra) ou corrija o cadastro e informe CPF/CNS normalmente.',
    repairClass: 'auto',
    implemented: true,
    ui: 'justificativa',
    focusField: 'justificativa',
    tipos: ['FAO', 'FAI'],
  },
  JUSTIFICATIVA_CPF_UNEXPECTED: {
    code: 'JUSTIFICATIVA_CPF_UNEXPECTED',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Justificativa de CPF sem marcar “não possui”',
    why: 'Há justificativa de não ter CPF, mas o campo “não possui CPF” não está marcado como verdadeiro. Isso é inconsistência: o Ministério pode rejeitar ou tratar o cadastro de forma errada.',
    how: 'Escolha: remover a justificativa, ou marcar stNaoPossuiCpf=true (cidadão realmente sem CPF).',
    repairClass: 'semi',
    implemented: true,
    ui: 'justificativa_unexpected',
    focusField: 'justificativaUnexpected',
    tipos: ['FAO', 'FAI'],
  },
  LOCAL_ATENDIMENTO: {
    code: 'LOCAL_ATENDIMENTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Local do atendimento inválido',
    why: 'É preciso dizer onde o atendimento aconteceu (UBS, domicílio, etc.) com um código válido. Local errado ou vazio = rejeição; a produção pode não ser creditada ao tipo de serviço certo.',
    how: 'Preencha um local válido (ex.: 1 = UBS). Confira a lista de locais permitidos na ficha.',
    repairClass: 'auto',
    implemented: true,
    ui: 'local',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  PATIENT_ID_MISSING: {
    code: 'PATIENT_ID_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Paciente sem identificação',
    why: 'Sem CPF, sem cartão do cidadão e sem marcar que a pessoa não tem CPF, o Ministério não sabe quem foi atendido. A ficha é rejeitada e aquele atendimento some da produção da cidade.',
    how: 'Informe CPF ou CNS do cidadão. Se realmente não houver CPF, marque o campo “não possui CPF” e preencha a justificativa.',
    repairClass: 'individual',
    implemented: true,
    ui: 'st_cpf',
    focusField: 'xml',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  PREVINE_B1_NO_FIRST_CONSULTA: {
    code: 'PREVINE_B1_NO_FIRST_CONSULTA',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem primeira consulta programada (indicador B1)',
    why: 'O indicador B1 do Previne Brasil mede quantas pessoas tiveram a 1ª consulta odontológica programada — a “entrada” da pessoa no cuidado com a equipe. Sem o procedimento certo dessa primeira consulta, a pessoa não entra no numerador. A cidade precisa desse número para a nota e a qualidade do indicador Previne.',
    how: 'Se de fato for a 1ª consulta programada da pessoa na equipe, peça ao dentista para incluir o código do procedimento de 1ª consulta programada (0301010153) e reexporte.',
    repairClass: 'auto',
    implemented: true,
    ui: 'proc_b1',
    tipos: ['FAO'],
  },
  PREVINE_B2_NO_CONCLUSAO: {
    code: 'PREVINE_B2_NO_CONCLUSAO',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem tratamento concluído (indicador B2)',
    why: 'O B2 mede resolutividade: entre quem começou tratamento (teve 1ª consulta), quantos concluíram. Aqui há sinal de início, mas falta a conduta de tratamento concluído. Sem fechar o par, a cidade mostra que “abriu” o cuidado e não “fechou” — a nota do Previne cai.',
    how: 'Ao concluir o plano de tratamento, registre a conduta de tratamento concluído (15) com tipo de consulta 1 ou 2. Peça ao dentista para não esquecer o fechamento na última consulta.',
    repairClass: 'auto',
    implemented: true,
    ui: 'encam_15',
    tipos: ['FAO'],
  },
  PREVINE_B2_NO_PAIR: {
    code: 'PREVINE_B2_NO_PAIR',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'Sem início nem conclusão de tratamento (B2)',
    why: 'O B2 é uma razão: concluídos ÷ primeiras consultas. Neste arquivo não há nenhum dos dois eventos. Pode ser normal (urgência, retorno sem fechar plano, etc.). Não é rejeição do Ministério — só aviso do raio-x Previne.',
    how: 'Informativo. Só aja se o atendimento deveria ser 1ª consulta programada ou conclusão de tratamento — aí peça ao dentista para registrar o procedimento/conduta certos.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B3_HIGH_EXODONTIA: {
    code: 'PREVINE_B3_HIGH_EXODONTIA',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Muita extração de dente (indicador B3)',
    why: 'O B3 mede a proporção de extrações. Neste recorte a razão extração/procedimentos está alta (≥ 14%, faixa Regular). Extração demais piora a nota do Previne: o programa quer menos perda de dente e mais cuidado preventivo/curativo que preserve o dente. Isso afeta o escore e a qualidade do indicador.',
    how: 'Revise se preventivos e tratamentos conservadores estão sendo registrados. Converse com a coordenação de odontologia sobre o perfil clínico do mês — não “esconda” extração necessária, mas garanta que limpeza, flúor e restaurações também entrem na ficha.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B3_LOW_EXODONTIA_SHARE: {
    code: 'PREVINE_B3_LOW_EXODONTIA_SHARE',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Pouca extração neste recorte (B3)',
    why: 'O B3 tem uma faixa “ótima” de proporção de extrações no período (em geral entre cerca de 3% e 10%). Neste atendimento a proporção local ficou abaixo. Pode ser só o perfil deste XML (muito preventivo) — não é rejeição, mas o raio-x avisa que o mix do mês merece olhar.',
    how: 'Informativo. Só ajuste se o mix clínico do período da equipe realmente estiver desalinhado; não force extração por indicador.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B3_NO_EXODONTIA: {
    code: 'PREVINE_B3_NO_EXODONTIA',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'Sem extração de dente neste atendimento (B3)',
    why: 'O B3 olha quanto das ações são extração de dente — o desejável é menos extração e mais prevenção. Este atendimento não tem extração; isso pode ser bom se o mix do mês for preventivo. É só informação do recorte local, não um erro de envio.',
    how: 'Informativo no XML. Olhe o mix do período na equipe (não só este arquivo) antes de mudar rotina.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B4_NOT_IN_FAO: {
    code: 'PREVINE_B4_NOT_IN_FAO',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'Escovação em grupo não entra nesta ficha (B4)',
    why: 'O B4 mede escovação supervisionada em grupo (ação coletiva). Esse indicador não entra na ficha odontológica individual — por isso o raio-x avisa que B4 não se resolve aqui. Para a nota do Previne, a cidade precisa registrar a atividade coletiva no fluxo certo.',
    how: 'Registre a escovação supervisionada na ficha/atividade coletiva correspondente (não nesta ficha individual). Oriente a equipe de saúde bucal a lançar o coletivo no módulo próprio.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B5_HIGH_PREVENTIVE: {
    code: 'PREVINE_B5_HIGH_PREVENTIVE',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Prevenção muito alta neste recorte (B5)',
    why: 'No B5, as duas pontas são problemáticas: muito baixo ou acima de ~85% também entra na faixa Regular. Pode ser só este atendimento cheio de prevenção — o importante é o equilíbrio do período da equipe para a nota do Previne.',
    how: 'Equilíbrio clínico no mix do período. Não remova prevenção real; confira se curativos feitos no mesmo período também estão sendo registrados.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B5_LOW_PREVENTIVE: {
    code: 'PREVINE_B5_LOW_PREVENTIVE',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Pouca prevenção no atendimento (B5)',
    why: 'A proporção de procedimentos preventivos ficou abaixo de 40% neste atendimento — abaixo do suficiente no B5. Isso sugere mix mais curativo/extração; a nota do Previne pode cair e a cidade perde pontos no cuidado preventivo.',
    how: 'Aumente o registro de preventivos quando forem feitos, em relação a só curativos/extração. Oriente a equipe a lançar flúor, limpeza e orientação sempre que ocorrerem.',
    repairClass: 'auto',
    implemented: true,
    ui: 'proc_prev',
    tipos: ['FAO'],
  },
  PREVINE_B5_NO_PREVENTIVE: {
    code: 'PREVINE_B5_NO_PREVENTIVE',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem ações de prevenção (indicador B5)',
    why: 'O B5 mede quanto do atendimento individual é prevenção (flúor, limpeza/profilaxia, orientação, selante, etc.). Zero preventivo neste arquivo puxa o indicador para baixo. A cidade precisa desse mix para a nota do Previne Brasil em saúde bucal.',
    how: 'Quando o profissional fizer prevenção, registre na ficha (flúor, selante, profilaxia, orientação…). Peça ao dentista para não lançar só curativo/extração se também fez prevenção no mesmo atendimento.',
    repairClass: 'auto',
    implemented: true,
    ui: 'proc_prev',
    tipos: ['FAO'],
  },
  PREVINE_B5_NO_PROCS: {
    code: 'PREVINE_B5_NO_PROCS',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Sem procedimentos para estimar prevenção (B5)',
    why: 'Não há procedimentos individuais reconhecidos neste XML, então o raio-x não consegue estimar o B5 (quanto do atendimento é prevenção). Sem códigos, a cidade não mostra o trabalho feito nos indicadores.',
    how: 'Confira se os códigos de procedimento foram preenchidos. Peça ao dentista para lançar o que foi realizado na consulta.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_B6_NO_ART: {
    code: 'PREVINE_B6_NO_ART',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Restauração sem técnica ART/TRA (indicador B6)',
    why: 'O B6 mede o uso de ART/TRA (técnica restauradora atraumática — restauração mais simples, sem broca em muitos casos) quando se restaura. Há restauração neste atendimento, mas nenhum procedimento ART. O numerador do B6 fica zerado aqui e a cidade deixa de pontuar esse cuidado no Previne.',
    how: 'Quando a técnica ART/TRA for a usada, peça ao dentista para registrar o código do procedimento ART (0307010074). Se não foi ART, o aviso só mostra que este caso não sobe o B6.',
    repairClass: 'auto',
    implemented: true,
    ui: 'proc_art',
    tipos: ['FAO'],
  },
  PREVINE_B6_NO_RESTORATIVE: {
    code: 'PREVINE_B6_NO_RESTORATIVE',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'B6 não se aplica neste atendimento',
    why: 'O B6 só entra na conta quando há procedimentos restauradores. Sem restauração neste XML, o indicador não é calculado para este atendimento — isso é esperado em consultas só de prevenção, urgência sem restauração, etc.',
    how: 'Informativo. Nenhuma ação obrigatória neste arquivo.',
    repairClass: 'info',
    implemented: true,
    tipos: ['FAO'],
  },
  PREVINE_CBO_NOT_ESB: {
    code: 'PREVINE_CBO_NOT_ESB',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Ocupação fora da equipe de saúde bucal',
    why: 'Os indicadores bucais do Previne só contam profissionais da família dentista/técnico/auxiliar de saúde bucal. Com ocupação de outra área, o atendimento pode ir no Siaps, mas não pontua a equipe de saúde bucal — a cidade deixa de somar no escore bucal.',
    how: 'Use a ocupação correta de dentista, TSB ou ASB elegível na lotação.',
    repairClass: 'auto',
    implemented: true,
    ui: 'cbo',
    tipos: ['FAO'],
  },
  PREVINE_INE_MISSING: {
    code: 'PREVINE_INE_MISSING',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Equipe sem código (impacto no Previne)',
    why: 'O Previne Brasil usa o código da equipe para saber a quem atribuir os indicadores de saúde bucal. Sem INE, mesmo que a ficha passe no envio, B1 (primeira consulta programada) e B4 (escovação em grupo) ficam inconsistentes — a cidade pode perder pontos e qualidade nos indicadores Previne.',
    how: 'Preencha o código da equipe de saúde bucal (INE) antes do envio final.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ine',
    tipos: ['FAO'],
  },
  PREVINE_PROBLEMAS_MISSING: {
    code: 'PREVINE_PROBLEMAS_MISSING',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem diagnóstico (qualidade Previne)',
    why: 'Além de poder bloquear o envio, ficha sem problema/condição empobrece a qualidade da informação usada nos indicadores. A cidade registra “atendeu”, mas não explica o perfil clínico — isso enfraquece análise e, em alguns filtros, o crédito nos indicadores.',
    how: 'Registre o CIAP/CID clínico real do atendimento. Peça ao dentista para não deixar diagnóstico em branco.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ciap',
    tipos: ['FAO'],
  },
  PREVINE_VIGILANCIA_99: {
    code: 'PREVINE_VIGILANCIA_99',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Vigilância só como “outro”',
    why: 'O código genérico “outro” esconde se havia cárie, problema de gengiva etc. Isso não bloqueia necessariamente o envio, mas piora o raio-x da saúde bucal da cidade e a qualidade do Previne.',
    how: 'Quando houver condição observada, troque pelo código específico de vigilância. Oriente o dentista a evitar o “outro” por comodidade.',
    repairClass: 'auto',
    implemented: true,
    ui: 'vigilancia',
    tipos: ['FAO'],
  },
  PROBLEMA_SEM_CODIGO: {
    code: 'PROBLEMA_SEM_CODIGO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Problema sem código clínico',
    why: 'Existe o bloco de problemas, mas sem código CIAP nem CID. É como escrever “há um problema” sem dizer qual — o Ministério rejeita e a informação clínica não serve para gestão.',
    how: 'Preencha um CIAP ou CID válido. Peça ao profissional para escolher o código clínico correto.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ciap',
    tipos: ['FAO'],
  },
  PROBLEMAS_MISSING: {
    code: 'PROBLEMAS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o problema ou diagnóstico',
    why: 'A ficha exige ao menos um código de problema/condição (CIAP e/ou CID). Sem isso, o Ministério rejeita. Além da rejeição, a cidade perde rastreio do que a população está apresentando.',
    how: 'Inclua problemas/condições com código CIAP e/ou CID. Peça ao profissional para registrar o motivo clínico do atendimento.',
    repairClass: 'auto',
    implemented: true,
    ui: 'ciap',
    tipos: ['FAO', 'FAI'],
  },
  PROC_ATENDIMENTO_MISSING: {
    code: 'PROC_ATENDIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Procedimentos sem atendimento',
    why: 'A ficha de procedimentos não traz o bloco de atendimento/procedimentos realizados.',
    how: 'Reexporte com os procedimentos lançados.',
    repairClass: 'reexport',
    implemented: true,
    tipos: ['PROC'],
  },
  PROC_CODE_ABPG: {
    code: 'PROC_CODE_ABPG',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Código ABPG não é SIGTAP',
    why: 'Códigos ABPG são internos do e-SUS e o Ministério rejeita no LEDI. A produção não entra.',
    how: 'Troque pelo código SIGTAP correspondente (10 dígitos) e reexporte ou corrija na ficha.',
    field: 'proc',
    repairClass: 'individual',
    implemented: true,
    focusField: 'proc',
    tipos: ['PROC'],
  },
  PROC_CODE_EMPTY: {
    code: 'PROC_CODE_EMPTY',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Procedimento sem código',
    why: 'Há um item de procedimento sem o código oficial do que foi feito (o código de procedimento do Ministério). Sem código, aquele ato não conta na produção nem nos indicadores — a cidade “trabalhou” mas não registra o serviço.',
    how: 'Preencha o código do procedimento com 10 dígitos. Peça ao dentista para lançar o procedimento correto na ficha.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'proc',
    tipos: ['FAO', 'PROC'],
  },
  PROC_CODE_FORMAT: {
    code: 'PROC_CODE_FORMAT',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Código de procedimento com formato inválido',
    why: 'O código SIGTAP deve ter 10 dígitos. Formato estranho pode falhar na aceitação da produção (Siaps).',
    how: 'Corrija para o código SIGTAP válido (10 dígitos).',
    field: 'proc',
    repairClass: 'individual',
    implemented: true,
    focusField: 'proc',
    tipos: ['PROC'],
  },
  PROC_DUPLICATE: {
    code: 'PROC_DUPLICATE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Mesmo procedimento repetido',
    why: 'O mesmo código de procedimento aparece mais de uma vez no atendimento. O Ministério rejeita duplicata — risco de perder a produção daquele paciente.',
    how: 'Some as quantidades em um único item ou remova a linha duplicada. Na tela/lote, revise a lista de procedimentos do atendimento.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'proc',
    tipos: ['FAO'],
  },
  PROC_ESCUTA_FORBIDDEN: {
    code: 'PROC_ESCUTA_FORBIDDEN',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Escuta inicial lançada no lugar errado',
    why: 'O código de escuta inicial não deve ir na lista de procedimentos desta ficha; o correto é marcar o tipo de atendimento adequado. Lançamento errado = rejeição e a escuta não conta do jeito certo.',
    how: 'Remova esse procedimento da lista e use o tipo de atendimento correto (escuta inicial). Peça ao dentista para ajustar o registro.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO'],
  },
  PROC_QTD: {
    code: 'PROC_QTD',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Quantidade do procedimento inválida',
    why: 'A quantidade precisa ser um número inteiro positivo. Quantidade zero, negativa ou estranha pode fazer o procedimento não contar na produção da cidade.',
    how: 'Normaliza quantidade para ≥ 1 (mínimo 1) no lote/auto-fix.',
    field: 'proc',
    repairClass: 'auto',
    implemented: true,
    focusField: 'proc',
    tipos: ['FAO', 'PROC', 'FAI'],
  },
  PROC_ROOT_NOT_FOUND: {
    code: 'PROC_ROOT_NOT_FOUND',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ficha de procedimentos incompleta',
    why: 'Faltam partes essenciais da ficha de procedimentos (tipo 7).',
    how: 'Reexporte o XML completo. Use a tela /faturamento/lote/proc.',
    repairClass: 'reexport',
    implemented: true,
    tipos: ['PROC'],
  },
  PROF_CNS_INVALID: {
    code: 'PROF_CNS_INVALID',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Cartão do profissional com número inválido',
    why: 'O CNS do profissional falhou na checagem matemática (dígito verificador). Em geral é erro de digitação no cadastro. Ficha com CNS errado pode ser rejeitada e a produção não entra.',
    how: 'Corrija o CNS no cadastro do profissional (confira no cartão físico ou no CNES) e gere o arquivo de novo.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  PROF_CNS_MISSING: {
    code: 'PROF_CNS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o cartão do profissional (CNS)',
    why: 'Todo atendimento precisa dizer qual profissional registrou. Sem o Cartão Nacional de Saúde do dentista/auxiliar, o Ministério não sabe quem trabalhou e rejeita a ficha — a produção não conta.',
    how: 'Na lotação do profissional, preencha o CNS. Se o cadastro estiver vazio, peça à gestão para completar no CNES/cadastro da unidade e reexporte.',
    field: 'headerTransport.lotacaoFormPrincipal.profissionalCNS',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  SEXO_INVALID: {
    code: 'SEXO_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Sexo inválido ou ausente',
    why: 'O campo sexo é obrigatório e só aceita masculino ou feminino no padrão da ficha. Valor estranho ou vazio faz o Ministério rejeitar o atendimento.',
    how: 'Corrija o campo sexo no atendimento (0 = masculino, 1 = feminino) e reexporte.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'sexo',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  ST_NAO_POSSUI_CPF: {
    code: 'ST_NAO_POSSUI_CPF',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta dizer se o cidadão tem CPF',
    why: 'O Ministério agora exige um campo sim/não explícito informando se o cidadão possui CPF. Mesmo que exista cartão do cidadão (CNS) na ficha, se esse campo estiver ausente a ficha é rejeitada. Em Franca isso já foi visto em 100% dos lotes antigos — é a causa mais comum de rejeição em massa.',
    how: 'Inclua o campo: false quando a pessoa tem CPF (ou você está usando CNS com a regra local); true quando realmente não tem CPF, e aí preencha também a justificativa.',
    repairClass: 'auto',
    implemented: true,
    ui: 'st_cpf',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  TIPO_ATENDIMENTO: {
    code: 'TIPO_ATENDIMENTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Tipo de atendimento inválido',
    why: 'O tipo (consulta, urgência, etc.) está fora do que esta ficha aceita. Sem tipo válido, o Ministério rejeita e aquele atendimento não conta.',
    how: 'Use um código de tipo de atendimento aceito nesta ficha (FAI tipo 4: 1, 2, 4, 5 ou 6). Peça ao profissional para classificar corretamente o atendimento.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  TIPO_CONSULTA_FORBIDDEN: {
    code: 'TIPO_CONSULTA_FORBIDDEN',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Tipo de consulta não permitido neste atendimento',
    why: 'O tipo de atendimento atual não admite o campo de tipo de consulta odontológica. Informação sobrando ou incompatível = rejeição pelo Ministério.',
    how: 'Remova o tipo de consulta odontológica ou mude o tipo de atendimento para um que permita esse campo.',
    repairClass: 'individual',
    implemented: true,
    focusField: 'consulta',
    tipos: ['FAO'],
  },
  TIPO_CONSULTA_MULTI: {
    code: 'TIPO_CONSULTA_MULTI',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Mais de um tipo de consulta',
    why: 'Só pode haver um tipo de consulta odontológica por atendimento. Com vários, o Ministério pode rejeitar ou a produção fica ambígua para os indicadores.',
    how: 'Mantém automaticamente só o primeiro tiposConsultaOdonto.',
    repairClass: 'auto',
    implemented: true,
    ui: 'consulta',
    tipos: ['FAO'],
  },
  TIPO_CONSULTA_REQUIRED: {
    code: 'TIPO_CONSULTA_REQUIRED',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta o tipo de consulta odontológica',
    why: 'Para certos tipos de atendimento (como consulta agendada), é obrigatório dizer se foi primeira consulta, retorno, etc. Sem isso, a ficha cai e indicadores de “entrada no cuidado” (Previne) não conseguem contar a pessoa.',
    how: 'Informe o tipo de consulta odontológica (1, 2 ou 4, conforme o caso). Peça ao dentista para classificar a consulta.',
    repairClass: 'auto',
    implemented: true,
    ui: 'consulta',
    tipos: ['FAO'],
  },
  TIPO_CONSULTA_URGENCIA: {
    code: 'TIPO_CONSULTA_URGENCIA',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Consulta incompatível com urgência',
    why: 'Urgência e tipo de consulta programada não combinam nessa regra. Misturar os dois faz o Ministério rejeitar — o atendimento não conta nem como urgência nem como consulta programada.',
    how: 'Ajuste: se for urgência, tire o tipo de consulta programada; se for consulta programada, use o tipo de atendimento correto.',
    field: 'consulta',
    repairClass: 'individual',
    implemented: true,
    focusField: 'consulta',
    tipos: ['FAO'],
  },
  TP_CDS_ORIGEM_MISSING: {
    code: 'TP_CDS_ORIGEM_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta informar de qual sistema veio a ficha',
    why: 'O Ministério exige um campo que diz qual sistema gerou a ficha. Sem esse marcador, o envio é rejeitado mesmo que o restante esteja certo.',
    how: 'Define tpCdsOrigem=3 (origem PEC/sistema terceiros) no auto-fix.',
    repairClass: 'auto',
    implemented: true,
    tipos: ['FAO', 'FAI'],
  },
  TP_CDS_ORIGEM_NOT_3: {
    code: 'TP_CDS_ORIGEM_NOT_3',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Origem do sistema diferente do esperado',
    why: 'Sistemas de terceiros, como o da cidade, em geral usam origem 3. Outro valor pode ser rejeitado no ambiente do município — risco de a produção não entrar.',
    how: 'Ajusta tpCdsOrigem para 3 no auto-fix.',
    repairClass: 'auto',
    implemented: true,
    tipos: ['FAO', 'FAI'],
  },
  TRATAMENTO_CONCLUIDO_RULE: {
    code: 'TRATAMENTO_CONCLUIDO_RULE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Tratamento concluído sem tipo de consulta adequado',
    why: 'A conduta “tratamento concluído” só vale se vier com tipo de consulta 1 ou 2. Sem esse par, o Ministério rejeita — e o indicador de resolutividade (Previne B2: entre quem começou, quantos terminaram) não consegue contar a conclusão.',
    how: 'Junto da conduta 15 (tratamento concluído), informe tipo de consulta 1 ou 2. Peça ao dentista para fechar o plano corretamente na ficha.',
    repairClass: 'auto',
    implemented: true,
    ui: 'encam_15',
    tipos: ['FAO'],
  },
  TURNO: {
    code: 'TURNO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Turno inválido ou ausente',
    why: 'O turno precisa ser manhã, tarde ou noite. Valor 0 (comum em sistemas antigos) é inválido. Sem turno certo, a ficha pode ser rejeitada.',
    how: 'Mapeie o turno corretamente no export (1 manhã, 2 tarde, 3 noite). Peça ao TI para corrigir o legado se vier zero.',
    repairClass: 'auto',
    implemented: true,
    ui: 'turno',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  UUID_FICHA_CASE: {
    code: 'UUID_FICHA_CASE',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'Número único da ficha em minúsculas',
    why: 'O identificador da ficha existe, mas não está em maiúsculas. O transporte LEDI costuma exigir o UUID canônico em maiúsculas.',
    how: 'Converte uuidFicha para maiúsculas sem mudar o valor.',
    repairClass: 'auto',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAI'],
  },
  UUID_FICHA_LENGTH: {
    code: 'UUID_FICHA_LENGTH',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Número único da ficha com tamanho errado',
    why: 'O identificador da ficha existe, mas está curto ou longo demais. O Ministério pode rejeitar e a produção daquele dia deixa de contar para a cidade.',
    how: 'Regenera uuidFicha no formato canônico CNES-UUID (36–44 chars) no auto-fix.',
    field: 'xml',
    repairClass: 'auto',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  UUID_FICHA_MISSING: {
    code: 'UUID_FICHA_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Ficha sem número único de identificação',
    why: 'Cada ficha precisa de um código único (como um “protocolo”) para o Ministério saber se é um atendimento novo ou uma reenvio. Sem esse código, o sistema federal não aceita o registro.',
    how: 'Peça ao gerador/export para preencher o identificador único da ficha (uuidFicha). Em geral isso é automático — se faltou, reexporte.',
    field: 'uuidFicha',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
  VIGILANCIA_MAX: {
    code: 'VIGILANCIA_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Vigilância com itens demais',
    why: 'Há um máximo de 7 códigos de vigilância. Acima disso, o Ministério pode rejeitar a ficha.',
    how: 'Trunca automaticamente para os 7 primeiros tiposVigilanciaSaudeBucal.',
    repairClass: 'auto',
    implemented: true,
    ui: 'vigilancia',
    tipos: ['FAO'],
  },
  VIGILANCIA_MISSING: {
    code: 'VIGILANCIA_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Falta a vigilância em saúde bucal',
    why: 'Na ficha odontológica é obrigatório registrar se o profissional observou condições de vigilância (cárie, gengiva, etc.). Sem esse campo, a ficha é rejeitada e a cidade perde informação útil para planejar prevenção.',
    how: 'Registre ao menos um código de vigilância em saúde bucal. Peça ao dentista para não deixar a seção em branco.',
    repairClass: 'auto',
    implemented: true,
    ui: 'vigilancia',
    tipos: ['FAO'],
  },
  WRONG_FICHA_TIPO: {
    code: 'WRONG_FICHA_TIPO',
    severity: 'BLOCKER',
    channel: 'LOTE',
    title: 'Tipo de ficha errado nesta tela',
    why: 'O arquivo é de outro tipo LEDI (FAO odonto tipo 5, FAI individual tipo 4 ou Procedimentos tipo 7). Cada tela só aceita o tipo correspondente — misturar atrasa o lote e pode mandar a produção para o lugar errado.',
    how: 'Separe os lotes: FAO em /faturamento/lote/fao, FAI (tipo 4) em /faturamento/lote/fai, Procedimentos em /faturamento/lote/proc.',
    field: 'tipoDadoSerializado',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI', 'PROC'],
  },
  XML_ENCODING: {
    code: 'XML_ENCODING',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'Encoding XML diferente de UTF-8',
    why: 'O arquivo não declara UTF-8. Caracteres acentuados podem corromper no Ministério e a ficha ser rejeitada.',
    how: 'Normaliza a declaração para encoding="utf-8".',
    repairClass: 'auto',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAI'],
  },
  XML_PARSE_ERROR: {
    code: 'XML_PARSE_ERROR',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Arquivo quebrado ou incompleto',
    why: 'O sistema não conseguiu abrir o arquivo de envio. Isso costuma acontecer quando o arquivo foi cortado no meio, salvo com erro ou veio corrompido no zip. Sem conseguir ler, a cidade não consegue enviar essa produção odontológica ao Ministério.',
    how: 'Peça ao setor de TI ou ao responsável pelo sistema legado para exportar o arquivo de novo. Confira se o zip não ficou incompleto ao baixar ou copiar.',
    repairClass: 'reexport',
    implemented: true,
    focusField: 'xml',
    tipos: ['FAO', 'FAI'],
  },
};

export function getLediError(code: string): LediErrorDef | undefined {
  return LEDI_ERROR_REGISTRY[code];
}

export function allLediErrorCodes(): string[] {
  return Object.keys(LEDI_ERROR_REGISTRY).sort();
}

export function repairClassOf(code: string): LediRepairClass | undefined {
  return LEDI_ERROR_REGISTRY[code]?.repairClass;
}

/** Modo efetivo na UI hoje (respeita implemented). */
export function effectiveRepairMode(code: string): LediRepairClass | undefined {
  const d = LEDI_ERROR_REGISTRY[code];
  if (!d) return undefined;
  // Até o fixer/UI de semi|auto estarem prontos, trata como individual (ou reexport).
  if (!d.implemented && (d.repairClass === 'auto' || d.repairClass === 'semi')) {
    return 'individual';
  }
  return d.repairClass;
}

export function autoFixableCodes(): string[] {
  return Object.values(LEDI_ERROR_REGISTRY)
    .filter((d) => d.repairClass === 'auto' && d.implemented)
    .map((d) => d.code)
    .sort();
}

export function coverageSummary() {
  const all = Object.values(LEDI_ERROR_REGISTRY);
  const by: Record<string, number> = { auto: 0, semi: 0, individual: 0, reexport: 0, info: 0 };
  const pending: string[] = [];
  for (const d of all) {
    by[d.repairClass] = (by[d.repairClass] || 0) + 1;
    if (!d.implemented) pending.push(d.code);
  }
  return { total: all.length, byClass: by, pendingImplement: pending.sort() };
}
