/** Catálogo municipal mínimo — demonstração (sem dados reais). */
export const MEDICATION_SEED = [
  {
    code: 'LOS50',
    name: 'Losartana potássica 50 mg',
    activePrinciple: 'Losartana',
    form: 'comprimido',
    concentration: '50 mg',
    defaultRoute: 'ORAL',
    recipeType: 'COMUM',
  },
  {
    code: 'MET850',
    name: 'Metformina 850 mg',
    activePrinciple: 'Metformina',
    form: 'comprimido',
    concentration: '850 mg',
    defaultRoute: 'ORAL',
    recipeType: 'COMUM',
  },
  {
    code: 'DIP500',
    name: 'Dipirona 500 mg',
    activePrinciple: 'Dipirona',
    form: 'comprimido',
    concentration: '500 mg',
    defaultRoute: 'ORAL',
    recipeType: 'COMUM',
  },
  {
    code: 'AMO500',
    name: 'Amoxicilina 500 mg',
    activePrinciple: 'Amoxicilina',
    form: 'cápsula',
    concentration: '500 mg',
    defaultRoute: 'ORAL',
    recipeType: 'COMUM',
  },
  {
    code: 'OME20',
    name: 'Omeprazol 20 mg',
    activePrinciple: 'Omeprazol',
    form: 'cápsula',
    concentration: '20 mg',
    defaultRoute: 'ORAL',
    recipeType: 'COMUM',
  },
  {
    code: 'ENOX40',
    name: 'Enoxaparina 40 mg',
    activePrinciple: 'Enoxaparina',
    form: 'injetável',
    concentration: '40 mg',
    defaultRoute: 'SC',
    recipeType: 'ESPECIAL',
    controlled: true,
  },
] as const;
