/**
 * Catálogo completo de códigos do parser/validador LEDI FAO + raio-x Previne.
 * Fonte: ledi-fao.validator.ts · ledi-fao-previne-xray.ts · lote (WRONG_FICHA_TIPO)
 */

export type ErrorSeverity = 'BLOCKER' | 'MONEY_RISK' | 'QUALITY_WARN' | 'INFO';

export type ErrorExplain = {
  code: string;
  severity: ErrorSeverity;
  channel: 'LEDI' | 'PREVINE' | 'LOTE';
  title: string;
  /** Por que o parser aponta isso */
  why: string;
  /** Como corrigir */
  how: string;
  field?: string;
};

export const ERROR_CATALOG: Record<string, ErrorExplain> = {
  // —— Formato / envelope ——
  XML_PARSE_ERROR: {
    code: 'XML_PARSE_ERROR',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'XML inválido',
    why: 'O arquivo não é XML bem formado (tag quebrada, encoding, etc.). O parser não consegue ler a árvore.',
    how: 'Reabra o arquivo no gerador/legado e exporte de novo; confira se não foi truncado no zip.',
  },
  FORMAT_FHIR_NOT_FAO: {
    code: 'FORMAT_FHIR_NOT_FAO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Bundle FHIR no lugar de FAO',
    why: 'O conteúdo parece FHIR R4 (RIA/RNDS). O canal odonto LEDI espera ficha FAO Thrift/XML CDS, não FHIR.',
    how: 'Use o export LEDI FAO (tipo 5), não o artefato FHIR RIA.',
  },
  FORMAT_DADO_TRANSPORT: {
    code: 'FORMAT_DADO_TRANSPORT',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Envelope sem FAO reconhecível',
    why: 'Há dadoTransporte, mas o validador não achou fichaAtendimentoOdontologicoMaster embutida.',
    how: 'Confirme tipoDadoSerializado=5 e a tag Master odonto no XML.',
  },
  FAO_ROOT_NOT_FOUND: {
    code: 'FAO_ROOT_NOT_FOUND',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Raiz sem FAO',
    why: 'A raiz XML não contém uuidFicha + headerTransport + atendimentosOdontologicos.',
    how: 'Envie XML FAO completo (não só um fragmento).',
  },
  WRONG_FICHA_TIPO: {
    code: 'WRONG_FICHA_TIPO',
    severity: 'BLOCKER',
    channel: 'LOTE',
    title: 'Tipo de ficha errado nesta tela',
    why: 'O arquivo é FAI (4), Procedimentos (7) ou outro tipo — não FAO (5). A tela /odonto/lote só corrige odonto.',
    how: 'Separe os lotes: FAO aqui; FAI/Procedimentos em fluxos próprios.',
    field: 'tipoDadoSerializado',
  },

  // —— Header / lotação ——
  UUID_FICHA_MISSING: {
    code: 'UUID_FICHA_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'uuidFicha ausente',
    why: 'Toda ficha LEDI precisa de identificador único (36–44 chars) para idempotência no Siaps.',
    how: 'Gerar UUID no export (uuidFicha / uuidDadoSerializado).',
    field: 'uuidFicha',
  },
  UUID_FICHA_LENGTH: {
    code: 'UUID_FICHA_LENGTH',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'uuidFicha com tamanho inválido',
    why: 'O LEDI FAO espera uuid entre 36 e 44 caracteres; fora disso há risco de rejeição.',
    how: 'Ajustar o gerador para o formato padrão do e-SUS.',
  },
  PROF_CNS_MISSING: {
    code: 'PROF_CNS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CNS do profissional ausente',
    why: 'A lotação (header) exige CNS do profissional que registrou o atendimento.',
    how: 'Preencher profissionalCNS na lotaçãoFormPrincipal.',
    field: 'headerTransport.lotacaoFormPrincipal.profissionalCNS',
  },
  PROF_CNS_INVALID: {
    code: 'PROF_CNS_INVALID',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'CNS do profissional inválido',
    why: 'O CNS falha no dígito verificador (módulo 11) — tipicamente digitação/cadastro.',
    how: 'Corrigir o CNS no cadastro do profissional e reexportar.',
  },
  CBO_MISSING: {
    code: 'CBO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CBO ausente',
    why: 'Sem CBO 2002 a ficha não identifica a ocupação elegível para FAO.',
    how: 'Informar cboCodigo_2002 na lotação (ex. 223208).',
  },
  CBO_NOT_ODONTO: {
    code: 'CBO_NOT_ODONTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CBO não permite FAO',
    why: 'O CBO informado não está na Tabela 4 (CBOs que podem registrar FAO — CD/TSB/ASB).',
    how: 'Trocar para CBO 2232xx ou 3224xx permitido na FAO.',
  },
  CNES_MISSING: {
    code: 'CNES_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CNES ausente',
    why: 'Produção APS precisa do CNES da unidade no header.',
    how: 'Preencher cnes / cnesDadoSerializado com 7 dígitos.',
  },
  CNES_FORMAT: {
    code: 'CNES_FORMAT',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'CNES com formato inválido',
    why: 'LEDI exige CNES com exatamente 7 dígitos (ex.: 8 dígitos do legado falham).',
    how: 'Usar o CNES oficial de 7 dígitos da unidade.',
  },
  IBGE_MISSING: {
    code: 'IBGE_MISSING',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'IBGE do município ausente',
    why: 'codigoIbgeMunicipio no header é necessário para territorializar a produção.',
    how: 'Cadastrar IBGE 7 dígitos (Franca = 3516200).',
  },
  IBGE_FORMAT: {
    code: 'IBGE_FORMAT',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'IBGE inválido',
    why: 'O código IBGE não tem 7 dígitos numéricos.',
    how: 'Corrigir o código do município no cadastro da unidade.',
  },
  INE_MISSING: {
    code: 'INE_MISSING',
    severity: 'QUALITY_WARN',
    channel: 'LEDI',
    title: 'INE ausente (LEDI)',
    why: 'Sem INE a equipe APS não fica amarrada na lotação — Siaps pode aceitar, mas APS/Previne fica inconsistente.',
    how: 'Preencher INE da eSB no envelope e na lotação.',
  },
  DATA_ATENDIMENTO_MISSING: {
    code: 'DATA_ATENDIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'dataAtendimento ausente',
    why: 'Header exige a data do atendimento (competência da produção).',
    how: 'Preencher dataAtendimento (epoch ms) no headerTransport.',
  },
  TP_CDS_ORIGEM_MISSING: {
    code: 'TP_CDS_ORIGEM_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'tpCdsOrigem ausente',
    why: 'Indica a origem do CDS (sistema gerador). Obrigatório no master FAO.',
    how: 'Exportar tpCdsOrigem (legado SIGS costuma usar 3).',
  },
  TP_CDS_ORIGEM_NOT_3: {
    code: 'TP_CDS_ORIGEM_NOT_3',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'tpCdsOrigem diferente de 3',
    why: 'Sistemas terceiros tipicamente usam origem 3; outro valor pode ser rejeitado conforme regra local.',
    how: 'Alinhar ao valor aceito no ambiente (geralmente 3).',
  },
  ATENDIMENTOS_EMPTY: {
    code: 'ATENDIMENTOS_EMPTY',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Sem atendimentos odontológicos',
    why: 'A ficha master precisa de 1–99 children atendimentosOdontologicos.',
    how: 'Incluir ao menos um bloco de atendimento no XML.',
  },
  ATENDIMENTOS_MAX: {
    code: 'ATENDIMENTOS_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Mais de 99 atendimentos',
    why: 'Limite LEDI FAO: no máximo 99 children por ficha.',
    how: 'Dividir em mais de uma ficha/master.',
  },

  // —— Cidadão / atendimento ——
  CPF_CNS_BOTH: {
    code: 'CPF_CNS_BOTH',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CPF e CNS juntos',
    why: 'Regra FAO: no mesmo atendimento informe CPF **ou** CNS, nunca os dois.',
    how: 'Manter só um identificador (preferência local/CNS).',
  },
  PATIENT_ID_MISSING: {
    code: 'PATIENT_ID_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Sem identificação do cidadão',
    why: 'Sem CPF/CNS e sem stNaoPossuiCpf=true a produção não individualiza a pessoa.',
    how: 'Informar CPF ou CNS, ou marcar stNaoPossuiCpf + justificativa.',
  },
  CPF_INVALID: {
    code: 'CPF_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CPF inválido',
    why: 'O CPF falha no algoritmo de dígitos verificadores.',
    how: 'Corrigir cadastro do cidadão ou usar CNS válido.',
  },
  CNS_INVALID: {
    code: 'CNS_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'CNS do cidadão inválido',
    why: 'CNS falha no módulo 11 — tipicamente erro de digitação no legado.',
    how: 'Corrigir CNS no cadastro ou usar CPF válido.',
  },
  ST_NAO_POSSUI_CPF: {
    code: 'ST_NAO_POSSUI_CPF',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'stNaoPossuiCpf ausente',
    why: 'Campo boolean obrigatório no LEDI recente: declara se o cidadão não possui CPF. Ausente = rejeição (visto em 100% dos lotes Franca).',
    how: 'Inserir false quando há CPF/CNS; true + justificativa quando não há CPF.',
  },
  JUSTIFICATIVA_CPF_MISSING: {
    code: 'JUSTIFICATIVA_CPF_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Justificativa de não-CPF ausente',
    why: 'Com stNaoPossuiCpf=true é obrigatório informar justificativaNaoPossuiCpf.',
    how: 'Preencher o código de justificativa conforme tabela LEDI.',
  },
  JUSTIFICATIVA_CPF_UNEXPECTED: {
    code: 'JUSTIFICATIVA_CPF_UNEXPECTED',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Justificativa de CPF inesperada',
    why: 'Há justificativa sem stNaoPossuiCpf=true — inconsistência de regra.',
    how: 'Remover justificativa ou marcar stNaoPossuiCpf corretamente.',
  },
  DT_NASCIMENTO_MISSING: {
    code: 'DT_NASCIMENTO_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Data de nascimento ausente',
    why: 'dtNascimento é obrigatória no atendimento individualizado.',
    how: 'Exportar data de nascimento do cadastro do cidadão.',
  },
  SEXO_INVALID: {
    code: 'SEXO_INVALID',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Sexo inválido/ausente',
    why: 'sexo deve ser 0 (masculino) ou 1 (feminino) conforme dicionário FAO.',
    how: 'Corrigir o campo sexo no atendimento.',
  },
  GESTANTE_MISSING: {
    code: 'GESTANTE_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Campo gestante ausente',
    why: 'Boolean gestante é obrigatório mesmo quando false.',
    how: 'Sempre emitir <gestante>true|false</gestante>.',
  },
  GESTANTE_SEXO_MASC: {
    code: 'GESTANTE_SEXO_MASC',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Gestante com sexo masculino',
    why: 'Inconsistência clínica/regra FAO: gestante=true com sexo masculino.',
    how: 'Corrigir sexo ou desmarcar gestante.',
  },
  LOCAL_ATENDIMENTO: {
    code: 'LOCAL_ATENDIMENTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'localAtendimento inválido',
    why: 'Deve ser código 1–10 da tabela de local de atendimento FAO.',
    how: 'Preencher local válido (ex.: 1 = UBS).',
  },
  TIPO_ATENDIMENTO: {
    code: 'TIPO_ATENDIMENTO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'tipoAtendimento inválido',
    why: 'Valor fora do domínio permitido para FAO (consulta, urgência, etc.).',
    how: 'Usar código de tipoAtendimento aceito na Tabela FAO.',
  },
  TURNO: {
    code: 'TURNO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Turno inválido/ausente',
    why: 'turno deve ser 1 (manhã), 2 (tarde) ou 3 (noite). Valor 0 do legado é inválido.',
    how: 'Mapear turno corretamente no export.',
  },
  CONDUTAS_MISSING: {
    code: 'CONDUTAS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Condutas (tiposEncamOdonto) ausentes',
    why: 'É obrigatório registrar ao menos uma conduta/encaminhamento odonto.',
    how: 'Incluir tiposEncamOdonto (códigos 1–17).',
  },
  CONDUTAS_MAX: {
    code: 'CONDUTAS_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Demasiadas condutas',
    why: 'Limite de itens em tiposEncamOdonto foi excedido (máx. 17).',
    how: 'Reduzir a lista de condutas ao essencial.',
  },
  VIGILANCIA_MISSING: {
    code: 'VIGILANCIA_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Vigilância saúde bucal ausente',
    why: 'tiposVigilanciaSaudeBucal é obrigatório na FAO (FAO#10).',
    how: 'Registrar ao menos um código de vigilância.',
  },
  VIGILANCIA_MAX: {
    code: 'VIGILANCIA_MAX',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Vigilância com itens demais',
    why: 'Excede o máximo de 7 códigos de vigilância.',
    how: 'Limitar a lista a no máximo 7.',
  },
  TIPO_CONSULTA_REQUIRED: {
    code: 'TIPO_CONSULTA_REQUIRED',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'tiposConsultaOdonto obrigatório',
    why: 'Para certos tipoAtendimento (ex. consulta agendada) a regra FAO exige tiposConsultaOdonto.',
    how: 'Informar tiposConsultaOdonto 1, 2 ou 4 conforme o caso.',
  },
  TIPO_CONSULTA_FORBIDDEN: {
    code: 'TIPO_CONSULTA_FORBIDDEN',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'tiposConsultaOdonto não permitido',
    why: 'O tipo de atendimento atual não admite tiposConsultaOdonto.',
    how: 'Remover tiposConsultaOdonto ou mudar tipoAtendimento.',
  },
  TIPO_CONSULTA_URGENCIA: {
    code: 'TIPO_CONSULTA_URGENCIA',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Consulta incompatível com urgência',
    why: 'Combinação indevida entre tipoAtendimento de urgência e tiposConsultaOdonto.',
    how: 'Ajustar conforme regras FAO de urgência × consulta.',
  },
  TIPO_CONSULTA_MULTI: {
    code: 'TIPO_CONSULTA_MULTI',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Mais de um tiposConsultaOdonto',
    why: 'O dicionário aceita no máximo 1 item nessa lista.',
    how: 'Manter apenas um código de consulta.',
  },
  TRATAMENTO_CONCLUIDO_RULE: {
    code: 'TRATAMENTO_CONCLUIDO_RULE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Conduta 15 sem consulta 1/2',
    why: 'Tratamento concluído (tiposEncamOdonto=15) exige tiposConsultaOdonto 1 ou 2.',
    how: 'Informar consulta 1 ou 2 junto da conduta 15.',
  },
  ALTA_EPISODIO_RULE: {
    code: 'ALTA_EPISODIO_RULE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Alta do episódio sem regra de consulta',
    why: 'Conduta de alta do episódio exige combinação válida com tiposConsultaOdonto.',
    how: 'Ajustar conduta e tipo de consulta conforme FAO#8.',
  },
  HORA_INI_MISSING: {
    code: 'HORA_INI_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Horário inicial ausente',
    why: 'dataHoraInicialAtendimento (epoch ms) é obrigatória.',
    how: 'Exportar início do atendimento.',
  },
  HORA_FIM_MISSING: {
    code: 'HORA_FIM_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Horário final ausente',
    why: 'dataHoraFinalAtendimento é obrigatória.',
    how: 'Exportar fim do atendimento.',
  },
  HORA_FIM_ANTES_INI: {
    code: 'HORA_FIM_ANTES_INI',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Fim antes do início',
    why: 'Horário final é anterior ao inicial — inconsistência temporal.',
    how: 'Corrigir as marcas de tempo no prontuário/export.',
  },
  HORA_INI_ANTES_DATA: {
    code: 'HORA_INI_ANTES_DATA',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Início antes da data do header',
    why: 'dataHoraInicialAtendimento anterior a dataAtendimento do header.',
    how: 'Alinhar data do header com o período do atendimento.',
  },
  PROC_CODE_EMPTY: {
    code: 'PROC_CODE_EMPTY',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Procedimento sem código',
    why: 'Há item em procedimentosRealizados sem coMsProcedimento.',
    how: 'Preencher SIGTAP 10 dígitos.',
  },
  PROC_ESCUTA_FORBIDDEN: {
    code: 'PROC_ESCUTA_FORBIDDEN',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Procedimento de escuta inicial proibido aqui',
    why: '0301040079 não deve ir em procedimentos — registra-se via tipoAtendimento=4.',
    how: 'Remover o proc e usar o tipo de atendimento correto.',
  },
  PROC_DUPLICATE: {
    code: 'PROC_DUPLICATE',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Procedimento duplicado',
    why: 'O mesmo coMsProcedimento aparece mais de uma vez no atendimento.',
    how: 'Somar quantidades em um único item ou remover duplicata.',
  },
  PROC_QTD: {
    code: 'PROC_QTD',
    severity: 'MONEY_RISK',
    channel: 'LEDI',
    title: 'Quantidade de procedimento inválida',
    why: 'quantidade deve ser inteiro positivo válido para o SIGTAP.',
    how: 'Corrigir a quantidade (≥ 1).',
  },
  PROBLEMAS_MISSING: {
    code: 'PROBLEMAS_MISSING',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'problemasCondicoes ausente',
    why: 'FAO exige ao menos um CIAP e/ou CID10 no atendimento (qualidade clínica + aceite LEDI).',
    how: 'Incluir problemasCondicoes com ciap e/ou cid10.',
  },
  PROBLEMA_SEM_CODIGO: {
    code: 'PROBLEMA_SEM_CODIGO',
    severity: 'BLOCKER',
    channel: 'LEDI',
    title: 'Problema sem CIAP/CID',
    why: 'Existe bloco problemasCondicoes, mas sem código CIAP nem CID10.',
    how: 'Preencher ciap ou cid10 válido.',
  },

  // —— Previne ——
  PREVINE_INE_MISSING: {
    code: 'PREVINE_INE_MISSING',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'INE ausente (Previne)',
    why: 'Sem INE os denominadores B1/B4 e o vínculo de equipe no Previne ficam inconsistentes — mesmo se o Siaps aceitar.',
    how: 'Preencher INE da eSB antes do envio final.',
  },
  PREVINE_CBO_NOT_ESB: {
    code: 'PREVINE_CBO_NOT_ESB',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'CBO fora da família ESB',
    why: 'Indicadores bucais filtram CBO 2232*/3224*. CBO fora da família não pontua ESB.',
    how: 'Usar CBO de dentista/TSB elegível.',
  },
  PREVINE_PROBLEMAS_MISSING: {
    code: 'PREVINE_PROBLEMAS_MISSING',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem CIAP/CID (qualidade Previne)',
    why: 'Além do blocker LEDI, a ausência de problema/condição reduz qualidade da informação para indicadores.',
    how: 'Registrar CIAP/CID clínico real.',
  },
  PREVINE_VIGILANCIA_99: {
    code: 'PREVINE_VIGILANCIA_99',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Vigilância só código 99',
    why: 'Código 99 = “outro” mascara vigilância específica (cárie, periodontal…) e empobrece análise.',
    how: 'Trocar por códigos específicos quando houver condição observada.',
  },
  PREVINE_B1_NO_FIRST_CONSULTA: {
    code: 'PREVINE_B1_NO_FIRST_CONSULTA',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem 1ª consulta programada (B1)',
    why: 'B1 conta pessoas com procedimento 03.01.01.015-3. Sem esse SIGTAP o numerador não sobe.',
    how: 'Se for 1ª consulta programada, incluir 0301010153.',
  },
  PREVINE_B2_NO_CONCLUSAO: {
    code: 'PREVINE_B2_NO_CONCLUSAO',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem tratamento concluído (B2)',
    why: 'Há 1ª consulta, mas sem conduta 15 — B2 (resolutividade) não conta o par.',
    how: 'Ao concluir o plano, registrar tiposEncamOdonto=15 com consulta 1 ou 2.',
  },
  PREVINE_B2_NO_PAIR: {
    code: 'PREVINE_B2_NO_PAIR',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'Sem par B1+B2',
    why: 'B2 é razão concluídos/1ªs consultas. Este XML não tem nenhum dos dois eventos.',
    how: 'Informativo — só agir se o atendimento deveria ser 1ª consulta ou conclusão.',
  },
  PREVINE_B3_NO_EXODONTIA: {
    code: 'PREVINE_B3_NO_EXODONTIA',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'Sem exodontia (recorte local)',
    why: 'B3 é taxa de exodontia no período. Este atendimento não tem exodontia — ok se o perfil for preventivo.',
    how: 'Informativo no XML; olhe o mix do período.',
  },
  PREVINE_B3_HIGH_EXODONTIA: {
    code: 'PREVINE_B3_HIGH_EXODONTIA',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Alta proporção de exodontia (B3)',
    why: 'Neste recorte a razão exodontia/procedimentos ≥ 14% (faixa Regular do B3).',
    how: 'Revisar se preventivos/curativos estão sendo registrados.',
  },
  PREVINE_B3_LOW_EXODONTIA_SHARE: {
    code: 'PREVINE_B3_LOW_EXODONTIA_SHARE',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Baixa proporção de exodontia (B3)',
    why: 'Proporção local abaixo da faixa ótima B3 (≥3% e <10%) neste atendimento.',
    how: 'Informativo — ajuste só se o mix clínico do período exigir.',
  },
  PREVINE_B5_NO_PREVENTIVE: {
    code: 'PREVINE_B5_NO_PREVENTIVE',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem preventivo (B5)',
    why: 'B5 mede participação de preventivos individuais. Zero preventivo neste XML puxa o indicador para baixo.',
    how: 'Registrar flúor, selante, profilaxia, orientação, etc.',
  },
  PREVINE_B5_LOW_PREVENTIVE: {
    code: 'PREVINE_B5_LOW_PREVENTIVE',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Poucos preventivos (B5)',
    why: 'Proporção de preventivos < 40% neste atendimento (abaixo do suficiente B5).',
    how: 'Aumentar registro de preventivos vs só curativos/exodontia.',
  },
  PREVINE_B5_HIGH_PREVENTIVE: {
    code: 'PREVINE_B5_HIGH_PREVENTIVE',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Preventivos muito altos (B5)',
    why: 'Acima de 85% também é Regular no B5 (as duas pontas).',
    how: 'Equilíbrio clínico no mix do período.',
  },
  PREVINE_B5_NO_PROCS: {
    code: 'PREVINE_B5_NO_PROCS',
    severity: 'QUALITY_WARN',
    channel: 'PREVINE',
    title: 'Sem procs para estimar B5',
    why: 'Não há procedimentos individuais reconhecidos no XML.',
    how: 'Conferir coMsProcedimento SIGTAP.',
  },
  PREVINE_B6_NO_ART: {
    code: 'PREVINE_B6_NO_ART',
    severity: 'MONEY_RISK',
    channel: 'PREVINE',
    title: 'Sem ART (B6)',
    why: 'Há restauração, mas nenhum ART 03.07.01.007-4 — numerador B6 fica zerado neste atendimento.',
    how: 'Quando aplicável, registrar TRA/ART 0307010074.',
  },
  PREVINE_B6_NO_RESTORATIVE: {
    code: 'PREVINE_B6_NO_RESTORATIVE',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'B6 não se aplica',
    why: 'Sem procedimentos restauradores neste XML, B6 não entra no cálculo deste atendimento.',
    how: 'Informativo.',
  },
  PREVINE_B4_NOT_IN_FAO: {
    code: 'PREVINE_B4_NOT_IN_FAO',
    severity: 'INFO',
    channel: 'PREVINE',
    title: 'B4 fora da FAO',
    why: 'Escovação supervisionada (B4) usa ação coletiva 01.01.02.003-1 — não entra na FAO individual.',
    how: 'Registrar em atividade coletiva / ficha correspondente.',
  },
};

export function explainError(code: string): ErrorExplain | undefined {
  return ERROR_CATALOG[code];
}

export function allErrorExplanations(): ErrorExplain[] {
  return Object.values(ERROR_CATALOG).sort((a, b) => a.code.localeCompare(b.code));
}
