/** Âncoras RF (Obrigatório/Desejável) para rastreio e testes de faturamento. */
export const RF = {
  FACILITY_LIST: { id: 'RF-2.47', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  PROFESSIONAL: { id: 'RF-2.2', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  TEAM: { id: 'RF-2.19', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  PATIENT: { id: 'RF-2.27', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  PATIENT_LIST: { id: 'RF-2.56', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  TERRITORY: { id: 'RF-2.29', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a' },
  AGENDA: { id: 'RF-2.17', tipo: 'Obrigatório', fonte: 'ambos', teste_faturamento: 'n/a', nota: 'Agenda / slots' },
  ENCOUNTER_ENTRY: {
    id: 'RF-3.1',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'n/a',
    nota: 'Entrada / fila',
  },
  ENCOUNTER_CLINICAL: {
    id: 'RF-3.24',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'previsto',
    nota: 'Atendimento clínico APS',
  },
  VACCINATION: {
    id: 'RF-14.1',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'automatizado',
    nota: 'Aplicação de vacinas',
  },
  AUTH: {
    id: 'RF-1.2',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Autenticação / acesso',
  },
  USERS: {
    id: 'RF-1.4',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Usuários e perfis',
  },
  REPORTS: {
    id: 'RF-16.1',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'n/a',
    nota: 'Relatórios operacionais',
  },
  AUDIT: { id: 'RF-1.14', tipo: 'Obrigatório', fonte: 'TR', teste_faturamento: 'n/a' },
  ESUS: { id: 'RF-10.3', tipo: 'Obrigatório', fonte: 'e-SUS', teste_faturamento: 'previsto' },
  PROD: { id: 'RF-10.20', tipo: 'Obrigatório', fonte: 'e-SUS', teste_faturamento: 'previsto' },
  BPA: {
    id: 'RF-10.4',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'automatizado',
    nota: 'Export BPA stub a partir de lotes de produção',
  },
  BILLING_AMB: {
    id: 'RF-9.2',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'previsto',
    nota: 'Faturar procedimentos ambulatoriais (BPA/APAC stub)',
  },
  ODONTO: {
    id: 'RF-12.1',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'previsto',
    nota: 'Agenda odonto + abertura encounter (MVP parcial)',
  },
  ODONTOGRAM_HISTORY: {
    id: 'RF-12.11',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'automatizado',
    nota: 'Histórico de odontogramas (mesmo paciente/unidade) + copiar snapshot para o atual',
  },
  ODONTOGRAM_PROCS: {
    id: 'RF-12.13',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'automatizado',
    nota: 'Procedimentos predefinidos no odontograma, marcáveis como concluídos',
  },
  HOME_CARE: {
    id: 'RF-3.54',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'previsto',
    nota: 'Atendimento domiciliar APS (stub MVP)',
  },
  COLLECTIVE: {
    id: 'RF-3.53',
    tipo: 'Obrigatório',
    fonte: 'ambos',
    teste_faturamento: 'previsto',
    nota: 'Ficha de atividade coletiva APS (stub MVP)',
  },
  SIGTAP: {
    id: 'RF-10.1',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'previsto',
    nota: 'Catálogo SIGTAP (seed mínimo + import stub)',
  },
  SIGTAP_IMPORT: {
    id: 'RF-9.1',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'automatizado',
    nota: 'Importação SIGTAP (JSON stub + TB_PROCEDIMENTO MS)',
  },
  SIGTAP_VALIDATE: {
    id: 'RF-9.5',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'automatizado',
    nota: 'Validação de procedimento contra catálogo SIGTAP',
  },
  QUEUE_PANEL: {
    id: 'RF-3.10',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Chamada do paciente em painel (texto)',
  },
  QUEUE_TOTEM: {
    id: 'RF-3.11',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Totem para retirada de senha',
  },
  QUEUE_CALL: {
    id: 'RF-3.23',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Chamada do paciente pelo painel',
  },
  PRESCRIPTION: {
    id: 'RF-3.33',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Prescrição de medicamentos (receituário APS)',
  },
  PRESCRIPTION_EMIT: {
    id: 'RF-3.67',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Emissão de receitas',
  },
  MED_PARAMS: {
    id: 'RF-2.11',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Parâmetros de medicamentos / tipo de receita',
  },
  REGULATION_COMPLEX: {
    id: 'RF-2.3',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Cadastro de complexo regulador (stub)',
  },
  REGULATION_REQUEST: {
    id: 'RF-3.52',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'previsto',
    nota: 'Solicitação gerando demanda na central de regulação',
  },
  REGULATION_PROTOCOL_ALERT: {
    id: 'RF-3.59',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Alerta de solicitação fora do protocolo municipal',
  },
  REGULATION_QUEUE: {
    id: 'RF-13.4',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Fila de regulação (lista operacional)',
  },
  REGULATION_DECIDE: {
    id: 'RF-13.8',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Regular / autorizar / negar solicitação',
  },
  REGULATION_PRE: {
    id: 'RF-13.2',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Procedimentos pré-regulados (catálogo seed)',
  },
  LOTATION: {
    id: 'RF-2.60',
    tipo: 'Obrigatório',
    fonte: 'TR',
    teste_faturamento: 'n/a',
    nota: 'Lotação / listagem de profissionais por unidade',
  },
} as const;

export const APPOINTMENT_STATUS = [
  'SCHEDULED',
  'PRESENT',
  'NO_SHOW',
  'DID_NOT_WAIT',
  'CANCELLED',
  'COMPLETED',
  'DELETED',
] as const;

export type AppointmentStatus = (typeof APPOINTMENT_STATUS)[number];

/** Fila D2 — design handoff */
export const ENCOUNTER_STATUS = [
  'WAITING',
  'INITIAL_LISTENING',
  'IN_PROGRESS',
  'WAITING_OBSERVATION',
  'IN_OBSERVATION',
  'COMPLETED',
  'DID_NOT_WAIT',
  'ABSCONDED',
] as const;

export type EncounterStatus = (typeof ENCOUNTER_STATUS)[number];

export const ENCOUNTER_ACTIVE_QUEUE: EncounterStatus[] = [
  'WAITING',
  'INITIAL_LISTENING',
  'IN_PROGRESS',
  'WAITING_OBSERVATION',
  'IN_OBSERVATION',
];
