export type HelpArticle = {
  id: string;
  title: string;
  module: string;
  version: string;
  updatedAt: string;
  summary: string;
  body: string;
};

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'plataforma.login',
    title: 'Entrar no SIGS',
    module: 'Plataforma',
    version: '1.0.0',
    updatedAt: '2026-08-10',
    summary: 'Como autenticar e selecionar a unidade de trabalho.',
    body: `Use e-mail e senha corporativos. Após o login, escolha a UBS se você atende em mais de uma unidade. A sessão usa token Bearer; ao sair, o token é removido do navegador.`,
  },
  {
    id: 'plataforma.painel',
    title: 'Painel inicial',
    module: 'Plataforma',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Resumo da unidade: fila, pacientes e lotes.',
    body: `O painel mostra contagens da unidade atual, a fila resumida e atalhos. Use Ctrl K (ou o campo de busca no topo) para ir à busca de pacientes. “Garantir dados demo” (perfil TI) cria a UBS Centro Demonstração sem dados reais.`,
  },
  {
    id: 'cadastros.pacientes',
    title: 'Cadastro de pacientes',
    module: 'Cadastros',
    version: '1.1.0',
    updatedAt: '2026-08-10',
    summary: 'Nome social, endereço, mãe/pai desconhecidos e óbito condicional.',
    body: `Nome social fica sempre visível. Informe endereço (logradouro, número, bairro, cidade, UF, CEP). CPF e CNS usam fonte monoespaçada. Marque "Desconhece" para mãe ou pai — o campo de texto é desabilitado. Se o paciente for falecido, informe data e certidão no painel de alerta.`,
  },
  {
    id: 'cadastros.unidades',
    title: 'Unidades e IBGE',
    module: 'Cadastros',
    version: '0.1.0',
    updatedAt: '2026-08-11',
    summary: 'CNES e código IBGE do município para produção LEDI.',
    body: `Em Unidades, selecione a UBS e informe o IBGE municipal (7 dígitos). Franca/SP = 3516200. Esse código vai para o header das fichas de produção. Sem IBGE, o pré-envio alerta risco de rejeição.`,
  },
  {
    id: 'cadastros.lotacao',
    title: 'Lotação de profissionais',
    module: 'Cadastros',
    version: '0.2.0',
    updatedAt: '2026-08-10',
    summary: 'Vínculo profissional × unidade × CBO (obrigatório para produção).',
    body: `Em Lotações, vincule um profissional à unidade atual com CBO (4–6 dígitos) e função. Equipe é opcional e deve pertencer à mesma unidade. Sem lotação ativa, finalizar consulta ou registrar vacina é bloqueado (produção LEDI exige CNS+CBO+CNES+INE).`,
  },
  {
    id: 'agenda.slots',
    title: 'Agenda e exclusão de slot',
    module: 'Agenda',
    version: '1.1.0',
    updatedAt: '2026-08-10',
    summary: 'Agenda da unidade · só excluir se Agendado.',
    body: `A lista e a criação de slots ficam no escopo da unidade selecionada. Status: Agendado, Presente na unidade, Não compareceu, Não aguardou, Cancelado, Realizado, Excluído. A exclusão só é permitida quando o status atual é Agendado.`,
  },
  {
    id: 'atendimento.fila',
    title: 'Fila de atendimento',
    module: 'Atendimento',
    version: '1.2.0',
    updatedAt: '2026-08-10',
    summary: 'Oito status da fila D2 e atendimento clínico SOAP.',
    body: `Status: Aguardando, Escuta inicial, Em atendimento, Aguardando observação, Em observação, Realizado, Não aguardou, Evadiu. Se o cidadão já estiver na fila do dia, “Entrar na fila” continua o mesmo atendimento (não cria duplicata). No atendimento clínico, registre SOAP, CIAP/CID e finalize com desfecho (Alta, Retorno…). O profissional precisa de lotação ativa na unidade para gerar o lote de produção.`,
  },
  {
    id: 'atendimento.prescricao',
    title: 'Prescrição e receitas',
    module: 'Atendimento',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Catálogo municipal, fora do padrão com alerta e emissão.',
    body: `No atendimento clínico, escolha um medicamento do catálogo ou digite fora do padrão (gera alerta). Dose, frequência, duração e via são obrigatórios no rascunho. Emita a receita em /prescricoes/:id — itens fora do padrão pedem confirmação (forceOffCatalog). Tipos: comum, especial e controle.`,
  },
  {
    id: 'regulacao.fila',
    title: 'Central de regulação',
    module: 'Regulação',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Solicitar procedimento, fila e decisão do regulador.',
    body: `No atendimento clínico, envie um procedimento pré-regulado (ou fora do protocolo com alerta). Em /regulacao o regulador vê a fila, classifica (verde/amarelo/vermelho/azul), autoriza, devolve por falta de dados ou nega com motivo. Alguns procedimentos exigem CID.`,
  },
  {
    id: 'coletivo.stub',
    title: 'Atividade coletiva',
    module: 'Ambulatorial',
    version: '0.3.0',
    updatedAt: '2026-08-11',
    summary: 'Ficha coletiva APS com produção LEDI v2.',
    body: `Registre educação em saúde ou reunião, informe tema, público-alvo e participantes (≥1). Finalizar exige lotação do profissional. Gera lote collective_activity (ids LEDI) — quantidade no BPA = participantes.`,
  },
  {
    id: 'vacinacao.aplicacao',
    title: 'Aplicação de vacina',
    module: 'Vacinação',
    version: '1.1.0',
    updatedAt: '2026-08-10',
    summary: 'Cascata Imunobiológico → Estratégia → Dose; regras BCG e Especial.',
    body: `Estratégia Especial exige CBO e CID-10. BCG exige informar se é comunicante de hanseníase. A aplicação gera lote de produção LEDI. A lista do dia respeita a unidade selecionada.`,
  },
  {
    id: 'relatorios.minimos',
    title: 'Relatórios mínimos',
    module: 'Relatórios',
    version: '1.1.0',
    updatedAt: '2026-08-10',
    summary: 'Atendimentos e vacinas por período.',
    body: `O período padrão é o mês corrente na unidade selecionada. Filtre e exporte CSV para conferência operacional.`,
  },
  {
    id: 'cadastros.territorio',
    title: 'Território APS',
    module: 'Cadastros',
    version: '1.0.0',
    updatedAt: '2026-08-10',
    summary: 'Equipes, microáreas e vínculo do paciente.',
    body: `Em Território você cria equipes na unidade atual, cadastra microáreas por equipe e vincula pacientes. A microárea, se informada, precisa pertencer à mesma equipe. Na ficha do paciente há um resumo dos vínculos e atalho para gerenciar.`,
  },
  {
    id: 'odonto.stub',
    title: 'Odontologia',
    module: 'Odontologia',
    version: '0.3.0',
    updatedAt: '2026-08-11',
    summary: 'Consulta odonto com produção LEDI v2.',
    body: `Informe paciente, dente e código SIGTAP. Finalize com desfecho (Alta→id 17). Exige lotação ativa. Gera lote dental_encounter com tiposEncamOdonto numéricos. Para validar/corrigir XMLs do município em lote, use Lote LEDI FAO.`,
  },
  {
    id: 'odonto.lote-ledi',
    title: 'Lote LEDI FAO — validar e corrigir XMLs',
    module: 'Odontologia',
    version: '1.0.0',
    updatedAt: '2026-08-12',
    summary: 'Upload de XMLs odonto, inconsistências, auto-correção e download ZIP.',
    body: `Em Odontologia → Lote LEDI FAO: (1) envie XMLs; (2) veja o funil Siaps/Previne e os gráficos — clique num código para filtrar; (3) cada alerta mostra **Por quê** e **Como corrigir**; (4) corrija em massa ou ficha a ficha. Catálogo completo: docs/conhecimento/17-catalogo-erros-parser-ledi-fao.md.`,
  },
  {
    id: 'ad.stub',
    title: 'Atenção domiciliar',
    module: 'Ambulatorial',
    version: '0.3.0',
    updatedAt: '2026-08-11',
    summary: 'Visita AD1/AD2/AD3 com produção LEDI v2.',
    body: `Escolha modalidade AD1/AD2/AD3, turno e procedimento. Finalize com lotação — lote home_care traz modalidade e desfecho em ids LEDI.`,
  },
  {
    id: 'producao.ledi',
    title: 'Produção e lotes LEDI',
    module: 'Produção',
    version: '1.7.0',
    updatedAt: '2026-08-11',
    summary: 'Pré-envio, lifecycle (erro/reprocessar) e BPA stub.',
    body: `Status: rascunho, pronto, enviado, erro. Avalie antes de enviar. Lotes com erro: corrija e use Reprocessar. Enviados podem ser Reabertos localmente. Finalize atendimento/vacina com lotação — o lote sai com CBO+CNS+CNES+INE+IBGE.`,
  },
  {
    id: 'sigtap.catalogo',
    title: 'Catálogo SIGTAP',
    module: 'Faturamento',
    version: '0.3.0',
    updatedAt: '2026-08-11',
    summary: 'Seed piloto local, JSON stub e import MS quando disponível.',
    body: `O catálogo local traz dezenas de códigos APS (consulta, vacina, odonto, AD, coletivo, regulação). Use “Sincronizar seed” se faltar código após atualização. Import MS (TB_PROCEDIMENTO) quando o DATASUS estiver no ar; senão use JSON stub.`,
  },
  {
    id: 'admin.usuarios',
    title: 'Usuários',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Criar contas e vincular perfis.',
    body: `Requer permissão de gestão de usuários. Informe nome, e-mail, senha e perfil (TI, gestor, profissional…).`,
  },
  {
    id: 'admin.grupos',
    title: 'Grupos e perfis',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Matriz de permissões por perfil.',
    body: `Tela de leitura dos perfis e permissões efetivas (ex.: production.manage, *). Edição avançada fica para iterações seguintes.`,
  },
  {
    id: 'admin.auditoria',
    title: 'Auditoria',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Log de ações com RF.',
    body: `Lista as últimas ações (login, finish encounter, export_bpa, import_ms…). Filtre por texto livre.`,
  },
  {
    id: 'fila.totem',
    title: 'Totem de senhas',
    module: 'Ambulatorial',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Emitir senha por tipo de serviço.',
    body: `Escolha o tipo (comum, prioritário, vacina, odonto). Opcionalmente vincule um paciente. A senha aparece no painel TV da unidade.`,
  },
  {
    id: 'fila.guiche',
    title: 'Guichê / chamada',
    module: 'Ambulatorial',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Chamar próxima senha no painel.',
    body: `Informe o guichê/consultório e chame a próxima (prioritário primeiro). Se a senha tiver paciente, pode abrir atendimento na fila APS.`,
  },
];
