export type HelpArticle = {
  id: string;
  title: string;
  module: string;
  version: string;
  updatedAt: string;
  summary: string;
  body: string;
};

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'plataforma.login',
    title: 'Entrar no SIGS',
    module: 'Plataforma',
    version: '1.0.0',
    updatedAt: '2026-08-10',
    summary: 'Como autenticar e selecionar a unidade de trabalho.',
    body: `Use e-mail e senha corporativos. Após o login, escolha a UBS se você atende em mais de uma unidade. A sessão usa token Bearer; ao sair, o token é removido do navegador.`,
  },
  {
    id: 'plataforma.painel',
    title: 'Painel inicial',
    module: 'Plataforma',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Resumo da unidade: fila, pacientes e lotes.',
    body: `O painel mostra contagens da unidade atual, a fila resumida e atalhos. Use Ctrl K (ou o campo de busca no topo) para ir à busca de pacientes. “Garantir dados demo” (perfil TI) cria a UBS Centro Demonstração sem dados reais.`,
  },
  {
    id: 'cadastros.pacientes',
    title: 'Cadastro de pacientes',
    module: 'Cadastros',
    version: '1.2.0',
    updatedAt: '2026-08-16',
    summary: 'Siaps (CPF/CNS/DN) + CDS RF-2.30 Previne na ficha; nome social e óbito condicional.',
    body: `Em /pacientes/novo e /pacientes/[id]: badge vermelho Siaps em nome civil, DN, sexo, mãe (ou Desconhece), CPF/CNS e óbito. Na ficha, bloco CDS (nacionalidade/IBGE, raça/cor, etnia, deficiência, NIS) usa laranja Previne/Indicador — qualidade de denominador, sem inventar BLOCKER LEDI. Manual: docs/manuais/usuario/cadastros/pacientes-territorio.md · convenção docs/manuais/campos-siaps-previne.md. Vínculos e domicílio CDS: atalho Território.`,
  },
  {
    id: 'cadastros.unidades',
    title: 'Unidades e IBGE',
    module: 'Cadastros',
    version: '0.1.0',
    updatedAt: '2026-08-11',
    summary: 'CNES e código IBGE do município para produção LEDI.',
    body: `Em Unidades, default = Rede Prefeitura (mantenedora) — natureza jurídica 1244 / CNPJ 47970769000104 (~59 ativas). Toggle «Todos IBGE» mostra a cidade (~545 ativas). Botão «Sincronizar rede municipal» importa só a Prefeitura (POST /v1/cnes/sync?gestao=municipal). API GET /v1/facilities?gestao=municipal&ibge=3516200. Auditoria: /cadastros/cnes-auditoria.`,
  },
  {
    id: 'cadastros.cnes-auditoria',
    title: 'Auditoria cadastro CNES',
    module: 'Cadastros',
    version: '0.3.0',
    updatedAt: '2026-08-16',
    summary: 'Checks Facility/Team vs snapshot CNES — escopo rede municipal (Prefeitura).',
    body: `Em /cadastros/cnes-auditoria: «Sincronizar rede municipal» (POST /v1/cnes/sync?gestao=municipal) se o escopo estiver 0/0; depois «Importar profissionais lotados» (POST /v1/cnes/sync-professionals). Critério unidades: natureza jurídica 1244 (+ CNPJ mantenedora 47970769000104 enriquecido). PF: nome+CNS+CBO+INE (público CNES). Contagens cidade vs filtrado no painel. Export CSV. Sem PHI. Railway: CNES_SYNC_ON_BOOT=1 (+ CNES_SYNC_PROFESSIONALS_ON_BOOT=1 opcional). Membros por equipe: /equipes.`,
  },
  {
    id: 'cadastros.equipes',
    title: 'Equipes e membros CNES',
    module: 'Cadastros',
    version: '0.1.0',
    updatedAt: '2026-08-16',
    summary: 'Lista equipes municipais, membros e profissionais em mais de uma equipe.',
    body: `Em /equipes: clique na equipe para ver membros (nome, CNS, CBO/função). Painel «Em mais de uma equipe» cruza lotações ativas. Tipos CNES com label (76 = EAP — Equipe de Atenção Primária). APIs: GET /v1/cnes/teams, /v1/cnes/teams/:id, /v1/cnes/multi-team, /v1/cnes/team-types. Pré-requisito: sync unidades/equipes + sync-professionals.`,
  },
  {
    id: 'cadastros.lotacao',
    title: 'Lotação de profissionais',
    module: 'Cadastros',
    version: '0.2.0',
    updatedAt: '2026-08-10',
    summary: 'Vínculo profissional × unidade × CBO (obrigatório para produção).',
    body: `Em Lotações, vincule um profissional à unidade atual com CBO (4–6 dígitos) e função. Equipe é opcional e deve pertencer à mesma unidade. Sem lotação ativa, finalizar consulta ou registrar vacina é bloqueado (produção LEDI exige CNS+CBO+CNES+INE). Para ver composição das equipes CNES: /equipes.`,
  },
  {
    id: 'agenda.slots',
    title: 'Agenda e exclusão de slot',
    module: 'Agenda',
    version: '1.2.0',
    updatedAt: '2026-08-13',
    summary: 'Agenda da unidade · clínicas em /odonto/agenda e /aps/agenda · só excluir se Agendado.',
    body: `A lista e a criação de slots em /agenda ficam no escopo da unidade. Para grade do dia e abertura de ficha, use Agenda odonto ou Agenda APS (consulta agendada tipo 2 vs encaixe tipo 5). Status: Agendado, Presente na unidade, Não compareceu, Não aguardou, Cancelado, Realizado, Excluído. A exclusão só é permitida quando o status atual é Agendado.`,
  },
  {
    id: 'aps.atendimento',
    title: 'Atendimento APS — ficha FAI',
    module: 'Atendimento',
    version: '0.3.0',
    updatedAt: '2026-08-16',
    summary:
      'FAI tipo 4: campos Siaps (vermelho) vs Previne (laranja), SOAP, antropometria, preview Siaps-ready e fila /faturamento/aps.',
    body: `Em /aps escolha paciente, profissional e lotação (INE obrigatório por padrão, como no odonto) — ou abra a partir de /aps/agenda (slot do dia: consulta agendada tipo 2 ou encaixe tipo 5). A ficha /aps/[id] é paralela ao /odonto — não mistura odontograma. Campos com badge vermelho Siaps (tipo/local, CIAP/CID, condutas, stNaoPossuiCpf) são obrigatórios para finalizar; laranja Previne/Indicador (turno, gestante, antropometria) orienta indicadores e não bloqueia se Siaps ok. Manual: docs/manuais/usuario/ambulatorial/atendimento-aps-fai-onda1.md · convenção docs/manuais/campos-siaps-previne.md. Finalizar e faturar exige zero BLOCKER e grava ProductionBatch individual_encounter. Pós-fechamento: fila /faturamento/aps e lote XML /faturamento/lote/fai.`,
  },
  {
    id: 'atendimento.fila',
    title: 'Fila de atendimento',
    module: 'Atendimento',
    version: '1.2.0',
    updatedAt: '2026-08-10',
    summary: 'Oito status da fila D2 e atendimento clínico SOAP.',
    body: `Status: Aguardando, Escuta inicial, Em atendimento, Aguardando observação, Em observação, Realizado, Não aguardou, Evadiu. Se o cidadão já estiver na fila do dia, “Entrar na fila” continua o mesmo atendimento (não cria duplicata). No atendimento clínico, registre SOAP, CIAP/CID e finalize com desfecho (Alta, Retorno…). O profissional precisa de lotação ativa na unidade para gerar o lote de produção.`,
  },
  {
    id: 'atendimento.prescricao',
    title: 'Prescrição e receitas',
    module: 'Atendimento',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Catálogo municipal, fora do padrão com alerta e emissão.',
    body: `No atendimento clínico, escolha um medicamento do catálogo ou digite fora do padrão (gera alerta). Dose, frequência, duração e via são obrigatórios no rascunho. Emita a receita em /prescricoes/:id — itens fora do padrão pedem confirmação (forceOffCatalog). Tipos: comum, especial e controle.`,
  },
  {
    id: 'regulacao.fila',
    title: 'Central de regulação',
    module: 'Regulação',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Solicitar procedimento, fila e decisão do regulador.',
    body: `No atendimento clínico, envie um procedimento pré-regulado (ou fora do protocolo com alerta). Em /regulacao o regulador vê a fila, classifica (verde/amarelo/vermelho/azul), autoriza, devolve por falta de dados ou nega com motivo. Alguns procedimentos exigem CID.`,
  },
  {
    id: 'coletivo.stub',
    title: 'Atividade coletiva',
    module: 'Ambulatorial',
    version: '0.4.0',
    updatedAt: '2026-08-16',
    summary: 'Ficha coletiva APS com destaque Siaps/Previne e produção LEDI v2.',
    body: `Registre educação em saúde ou reunião. Badge vermelho Siaps: tipo, tema, público e nº de participantes (≥1, COLLECTIVE_QTY). Laranja Previne: turno e procedimento SIGTAP (ex. escovação 0101050011 → B4). Manual: docs/manuais/usuario/ambulatorial/atividade-coletiva.md. Finalizar exige lotação do profissional. Gera lote collective_activity — quantidade no BPA = participantes.`,
  },
  {
    id: 'vacinacao.aplicacao',
    title: 'Aplicação de vacina',
    module: 'Vacinação',
    version: '1.3.0',
    updatedAt: '2026-08-16',
    summary: 'Cascata imuno→estratégia→dose com campos Siaps (vermelho); estoque/frio MVP.',
    body: `Em /vacinacao aba Aplicar: paciente, imunobiológico, estratégia, dose, lote, fabricante, via e local têm badge Siaps (vermelho) — VAC_IMUNO_MISSING / VAC_LOT_MISSING no pré-envio. Estratégia Especial exige CBO e CID. Manual: docs/manuais/usuario/vacinacao/aplicacao.md. A aplicação gera lote vaccination; estoque do mesmo lote baixa qty; anulação devolve. Lista do dia respeita a unidade.`,
  },
  {
    id: 'relatorios.minimos',
    title: 'Relatórios mínimos',
    module: 'Relatórios',
    version: '1.1.0',
    updatedAt: '2026-08-10',
    summary: 'Atendimentos e vacinas por período.',
    body: `O período padrão é o mês corrente na unidade selecionada. Filtre e exporte CSV para conferência operacional.`,
  },
  {
    id: 'cadastros.territorio',
    title: 'Território APS',
    module: 'Cadastros',
    version: '1.3.0',
    updatedAt: '2026-08-16',
    summary: 'Vínculos Previne + domicílio/visita ACS com FieldHint Siaps.',
    body: `Em /territorio: vínculos paciente↔equipe com badge Previne (denominador). Domicílio CDS: Siaps em equipe, tipo de imóvel, logradouro e responsável. Visita ACS: Siaps em paciente/domicílio, desfecho e motivos; turno e lat/long em Previne (RF-17.12 → link OSM). Manual: docs/manuais/usuario/cadastros/pacientes-territorio.md. Sem mapa embutido e sem lote XML nesta fase.`,
  },
  {
    id: 'odonto.atendimento',
    title: 'Atendimento odontológico',
    module: 'Odontologia',
    version: '1.8.0',
    updatedAt: '2026-08-16',
    summary:
      'FAO com campos Siaps (vermelho) × Previne (laranja), odontograma, ciclo tratamento e fila /faturamento/odonto.',
    body: `Em /odonto escolha paciente, profissional e lotação — ou abra a partir de /odonto/agenda. Na ficha /odonto/[id]: legenda Siaps (vermelho) vs Previne (laranja). Obrigatórios Siaps: stNaoPossuiCpf, tipo/local, CIAP/CID, vigilância, condutas. Previne: turno, SIGTAP B1–B6, conduta 15 (B2), vigilância só 99 (aviso). Concluir consulta exige zero BLOCKER Siaps. Manual: docs/manuais/usuario/odonto/atendimento-onda1.md · convenção docs/manuais/campos-siaps-previne.md.`,
  },
  {
    id: 'odonto.agenda',
    title: 'Agenda odontológica',
    module: 'Odontologia',
    version: '0.2.0',
    updatedAt: '2026-08-13',
    summary: 'Grade do dia, consulta agendada vs encaixe, abrir ficha odonto a partir do slot (RF-12.1).',
    body: `Em /odonto/agenda filtre o dia da unidade. A vista padrão é a grade (horários × profissional, faixa 07:00–19:00). Crie Consulta agendada (LEDI tipoAtendimento=2) ou Encaixe / consulta no dia (tipo 5). Abrir cria o DentalEncounter vinculado ao slot, marca Presente e leva a /odonto/[id]. Falta marca NO_SHOW. Slots da linha APS não abrem aqui — use /aps/agenda. Não cobre cadastro livre de tipos de item, salas, grade municipal compartilhada nem SAMU.`,
  },
  {
    id: 'aps.agenda',
    title: 'Agenda APS',
    module: 'Atendimento',
    version: '0.1.0',
    updatedAt: '2026-08-13',
    summary: 'Mesmo modelo de slot da odonto: grade do dia e abertura da ficha FAI (RF-3.5).',
    body: `Em /aps/agenda a grade e os tipos de item são os mesmos da agenda odonto (consulta agendada = tipo 2, encaixe = tipo 5). Abrir cria Encounter origem FAI vinculado ao slot e navega para /aps/[id]. Abertura espontânea sem agenda continua em /aps. Slots marcados como odonto não abrem FAI. Sem SAMU, sem cadastro TR completo de tipos de item.`,
  },
  {
    id: 'odonto.stub',
    title: 'Odontologia',
    module: 'Odontologia',
    version: '0.5.0',
    updatedAt: '2026-08-12',
    summary: 'Alias — ver odonto.atendimento / odonto.agenda.',
    body: `Fluxo: /odonto/agenda (agendado) ou /odonto (espontâneo) → /odonto/[id] → /faturamento/odonto. Ajuda: odonto.atendimento · odonto.agenda.`,
  },
  {
    id: 'faturamento.hub',
    title: 'Faturamento & Validação',
    module: 'Faturamento',
    version: '0.7.0',
    updatedAt: '2026-08-16',
    summary: 'Hub: filas odonto/APS + lotes LEDI live/stub + auditoria + BPA.',
    body: `Em /faturamento: (1) Fila odonto — FAO; (2) Fila APS — FAI tipo 4; (3) Lotes LEDI live — FAO (5), FAI (4), Procedimentos (7) com wizard ZIP; (4) Stubs CDS — domicílio (3), visita ACS (8), AD (10) sem upload até amostra XML; (5) Auditoria (/faturamento/auditoria); (6) Produção/BPA. API catálogo: GET /v1/faturamento/ledi-cds-lotes. Desenho: docs/planejamento/desenho-lote-ledi-cds-3-8-10.md.`,
  },
  {
    id: 'faturamento.lote-cds-stub',
    title: 'Lote CDS stub (domicílio / visita ACS / AD)',
    module: 'Faturamento',
    version: '0.1.0',
    updatedAt: '2026-08-16',
    summary: 'Telas informativas tipos 3/8/10 — sem wizard ZIP nesta fase.',
    body: `Em /faturamento/lote/domicilio · /visita-acs · /ad: só orientação (código + tag + link à origem nativa). Dump Franca não trouxe esses XMLs. Gate dos lotes 4/5/7 detecta e recusa ZIP misto. Use /territorio ou /ad para registrar. Wizard real exige amostra municipal — ver desenho-lote-ledi-cds-3-8-10.md.`,
  },
  {
    id: 'faturamento.auditoria',
    title: 'Auditoria de faturamento',
    module: 'Faturamento',
    version: '0.2.0',
    updatedAt: '2026-08-16',
    summary: 'Cruzamento produção × rede municipal CNES/INE/CNS/CBO/SIGTAP por competência.',
    body: `Em /faturamento/auditoria escolha a competência (YYYY-MM). Escopo default = rede municipal (Prefeitura; natureza jurídica 1244). API GET /v1/faturamento/audit?competencia=&ibge=3516200&gestao=municipal analisa lotes nativos, ProductionRecord e encounters. Severidade blocker bloqueia envio; quality é qualidade/Previne. Checks: CNES ativo na rede municipal, INE, CNS/CBO vs lotação, SIGTAP, CIAP, conduta. Contagens mostram municipal vs cidade. gestao=todos usa todos os CNES do município. Export CSV. Sem PHI. Não altera o wizard LEDI.`,
  },
  {
    id: 'faturamento.fila-aps',
    title: 'Fila de faturamento APS',
    module: 'Faturamento',
    version: '0.1.0',
    updatedAt: '2026-08-13',
    summary: 'Produção do mês da ficha FAI tipo 4: competência, buckets LEDI, deep-link e lote FAI.',
    body: `Em /faturamento/aps veja os atendimentos APS da competência (unidade atual). Cores iguais ao lote FAI: bloqueia envio, qualidade incompleta, indicadores, em preenchimento, pronto. Atualizar revalida pendências; Revalidar pendências faz sync em lote. Deep-link: ?encounterId= e ?batchId= (Tela C em /aps/[id] após finalizar). XML importado / ZIP: /faturamento/lote/fai. Alias: /aps/faturamento.`,
  },
  {
    id: 'odonto.lote-ledi',
    title: 'Lote LEDI FAO — validar e corrigir XMLs',
    module: 'Odontologia',
    version: '1.2.0',
    updatedAt: '2026-08-12',
    summary: 'Upload de XMLs odonto, inconsistências, auto-correção e download ZIP.',
    body: `Em Faturamento → Tratamento de lotes LEDI → Lote FAO (/faturamento/lote/fao): wizard único (upload → gate de tipo → análise com gráfico → problema a problema → fechamento antes×depois → dois ZIPs: aptos para envio e ainda precisam correção → ficha a ficha). Pronto Siaps ≠ Pronto Previne ≠ 100% OK. ZIP do tipo errado é recusado e não analisa. Alias: /odonto/lote. Irmãos: FAI e Procedimentos.`,
  },
  {
    id: 'faturamento.lote-fai',
    title: 'Lote LEDI FAI — atendimento individual',
    module: 'Faturamento',
    version: '0.2.1',
    updatedAt: '2026-08-14',
    summary: 'Upload/validação de XMLs FAI (tipo 4), correção e export ZIP.',
    body: `Em /faturamento/lote/fai: wizard de lote FAI tipo 4 (não é odonto). (1) Envie o ZIP — o sistema abre ficha a ficha; auto vs pessoa; Pronto Siaps ≠ Pronto Previne ≠ 100% OK. (2) Se o ZIP for FAO/PROC, a tela recusa e volta ao início (não analisa). (3) Análise: quantidade, já podem enviar, erros, corrigem em lote vs individuais. (4) Modal sequencial problema a problema. (5) Fechamento: campos corrigidos + gráfico antes×depois. (6) Dois ZIPs: aptos-envio e pendentes. (7) Residual ficha a ficha. Safari: fatias 512 KiB no rodapé da etapa 1; não monta o ZIP na RAM. Fila nativa: /faturamento/aps. Alias: /aps/lote.`,
  },
  {
    id: 'faturamento.lote-proc',
    title: 'Lote LEDI Procedimentos',
    module: 'Faturamento',
    version: '0.1.0',
    updatedAt: '2026-08-12',
    summary: 'Upload/validação de XMLs de Procedimentos (tipo 7) e export ZIP.',
    body: `Em /faturamento/lote/proc: mesmo wizard das telas FAI/FAO (upload → gate de tipo 7 → análise → problema a problema → dois ZIPs aptos/pendentes → ficha a ficha). Priorize CPF/CNS, turno e CNES; ABPG/SIGTAP na ficha. Alias: /procedimentos/lote. Hub: /faturamento.`,
  },
  {
    id: 'ad.stub',
    title: 'Atenção domiciliar',
    module: 'Ambulatorial',
    version: '0.4.0',
    updatedAt: '2026-08-16',
    summary: 'Visita AD1/AD2/AD3 com campos Siaps/Previne e produção LEDI v2.',
    body: `Em /ad: cidadãos (≥1), modalidade AD e procedimento têm badge Siaps (vermelho). Turno, tipo, desfecho e CIAP/CID são Indicador (laranja — QUALITY_WARN no preflight). Use Preflight antes de Finalizar — lote home_care com N atendimentosDomiciliares. Manual: docs/manuais/usuario/ambulatorial/atencao-domiciliar.md.`,
  },
  {
    id: 'producao.ledi',
    title: 'Produção e lotes LEDI',
    module: 'Produção',
    version: '1.7.0',
    updatedAt: '2026-08-11',
    summary: 'Pré-envio, lifecycle (erro/reprocessar) e BPA stub.',
    body: `Status: rascunho, pronto, enviado, erro. Avalie antes de enviar. Lotes com erro: corrija e use Reprocessar. Enviados podem ser Reabertos localmente. Finalize atendimento/vacina com lotação — o lote sai com CBO+CNS+CNES+INE+IBGE.`,
  },
  {
    id: 'sigtap.catalogo',
    title: 'Catálogo SIGTAP',
    module: 'Faturamento',
    version: '0.3.0',
    updatedAt: '2026-08-11',
    summary: 'Seed piloto local, JSON stub e import MS quando disponível.',
    body: `O catálogo local traz dezenas de códigos APS (consulta, vacina, odonto, AD, coletivo, regulação). Use “Sincronizar seed” se faltar código após atualização. Import MS (TB_PROCEDIMENTO) quando o DATASUS estiver no ar; senão use JSON stub.`,
  },
  {
    id: 'admin.usuarios',
    title: 'Usuários',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Criar contas e vincular perfis.',
    body: `Requer permissão de gestão de usuários. Informe nome, e-mail, senha e perfil (TI, gestor, profissional…).`,
  },
  {
    id: 'admin.grupos',
    title: 'Grupos e perfis',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Matriz de permissões por perfil.',
    body: `Tela de leitura dos perfis e permissões efetivas (ex.: production.manage, *). Edição avançada fica para iterações seguintes.`,
  },
  {
    id: 'admin.auditoria',
    title: 'Auditoria',
    module: 'Administração',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Log de ações com RF.',
    body: `Lista as últimas ações (login, finish encounter, export_bpa, import_ms…). Filtre por texto livre.`,
  },
  {
    id: 'fila.totem',
    title: 'Totem de senhas',
    module: 'Ambulatorial',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Emitir senha por tipo de serviço.',
    body: `Escolha o tipo (comum, prioritário, vacina, odonto). Opcionalmente vincule um paciente. A senha aparece no painel TV da unidade.`,
  },
  {
    id: 'fila.guiche',
    title: 'Guichê / chamada',
    module: 'Ambulatorial',
    version: '0.1.0',
    updatedAt: '2026-08-10',
    summary: 'Chamar próxima senha no painel.',
    body: `Informe o guichê/consultório e chame a próxima (prioritário primeiro). Se a senha tiver paciente, pode abrir atendimento na fila APS.`,
  },
];
